### ISSUE TITLE
Search page reacts too quickly to text input

### ISSUE THREAD

**Issue by cjones051073** [macports/macports-webapp#105]
when searching for a port on 

https://ports.macports.org/

The page currently reacts instantaneously to each character typed into the search box. This means, if the user is entering a long port name, the page constantly 'flickers' on each character, which is quite distracting.

I would suggest putting a short delay in so the page does no react immediately to text input. A pause of only a fraction of a second should be enough to allow the user to enter the whole search string they want, before the page then reacts.

**Comment by cjones051073** [comment]
Alternatively, the search should only be performed when the user hits 'return'.

**Comment by pmetzger** [comment]
Generally, the right thing here is to delay a few ms to see if another character gets typed, and only do something once nothing has been typed for a little bit.

**Comment by cjones051073** [comment]
> Generally, the right thing here is to delay a few ms to see if another character gets typed, and only do something once nothing has been typed for a little bit.

Yeah, thats exactly what I am proposing.

**Comment by neverpanic** [comment]
And while we're at it, maybe we can also move the keyboard focus into the search bar on page load, so people can immediately start typing?

**Comment by arjunsalyan** [comment]
Thank you.
I have done the changes: https://github.com/macports/macports-webapp/pull/107

These have also been deployed here: http://ec2-52-34-234-111.us-west-2.compute.amazonaws.com

You might need to hard refresh or clear website data to see the changes.
The search triggers when a user does not press any key for 1000ms.

**Comment by pmetzger** [comment]
BTW, I note that ports.ocaml.org and the test site seem to not notice that a bunch of ports have been removed? Is that expected?

**Comment by arjunsalyan** [comment]
The website knows which ports have been removed by making the field `active=False` in the database. However, the PR to display a message on the port page that the port has been deleted is not merged yet.

We do not remove a deleted port from our database unless a new port by the same name replaces it, and simply show a message that this port has been deleted.

**Comment by pmetzger** [comment]
This seems like an odd choice; it would mean that (for example) there would be huge numbers of "ghost" ports that you would hit while searching, clogging up what you are trying to look for. (The overwhelming bulk of OCaml ports are gone, for example. Finding the ones that are actually there is now hard.) Maybe showing deleted ports could be an option instead of the default?

**Comment by cjones051073** [comment]
When will this be push out to the main production server, https://ports.macports.org ? That page still has the issue.

**Comment by mojca** [comment]
It seems to work as intended for me.
The updates run every N hours (I should check what N is exactly).

The footer prints the info about when port information / builds / statistics was last changed, but now when the app itself was last updated.

**Comment by neverpanic** [comment]
N=5

**Comment by arjunsalyan** [comment]
This commit has been deployed to production. The changes were mostly on the JavaScript end, so unless your browser refreshes the website data (or you manually do a hard refresh) the changes will not be visible.
