### ISSUE TITLE
Don't display deleted ports unless the user asks you to

### ISSUE THREAD

**Issue by pmetzger** [macports/macports-webapp#110]
Most of the time, if I'm searching MacPorts I'm looking for information about ports that are currently in the tree. It is relatively rare that I want to see data on deleted ports. So, I'd like to ask that unless the user checks a box or otherwise indicates they want to see deleted ports as well, that the deleted ports not be shown.

**Comment by arjunsalyan** [comment]
Thank you, I wrote a comment relating to this in #108 .

@mojca

**Comment by pmetzger** [comment]
Hi, just curious if this can be acted on? I'm finding it much harder working with (for example) the ocaml part of the tree where I got rid of a lot of obsolete ports because I can't filter the deleted ones out...

**Comment by arjunsalyan** [comment]
I am working on it, there was a bug that prevented the deleted ports from getting detected, it just got fixed yesterday.
I will add the functionality to filter out deleted ports by this weekend.

**Comment by pmetzger** [comment]
Thank you so much, @arjunsalyan!

**Comment by arjunsalyan** [comment]
I have deployed a test version (a checkbox below the search bar):
http://ec2-52-34-234-111.us-west-2.compute.amazonaws.com/

Could you please see if it works fine and satisfies the requirement?
You may need to clear website data or do a hard refresh before it works as expected!

**Comment by pmetzger** [comment]
Seems good to me...

**Comment by mojca** [comment]
See also #283.

**Comment by mascguy** [comment]
I definitely would prefer that deleted ports be hidden by default, with the current checkbox changed to "Show deleted ports." (Disabled by default.)

Indeed, checking the box to hide deleted ports is a necessity for me personally, as there are a boatload of openmpi-* and mpich-* subports that were removed last year.

Just curious, why was this closed? Is the intention to implement this as part of #283?

EDIT: Never Mind, inverting this is indeed covered by 283. Sorry folks!
