### ISSUE TITLE
Strange x axis sorting for installed port versions chart

### ISSUE THREAD

**Issue by cjones051073** [macports/macports-webapp#112]
Sorting of the port versions in the chart showing the installed versions appears to be done in decreasing order of frequency, so the version with the most stats on the left, least on the right. In my opinion this is a strange inconvenient scheme. It would be better to sort accordingly to the version itself, so oldest in the left, newest in the right.

See attached screen shot taken from

https://ports.macports.org/port/clang-8.0/stats?days=30&days_ago=0

<img width="464" alt="PNG image" src="https://user-images.githubusercontent.com/17502689/65144823-0e8d8b80-da10-11e9-9d3c-93c09e477f24.png">

My suggestion would flip 8.0.0_0 with 8.0.0_1

**Comment by arjunsalyan** [comment]
Thank you for reporting this. Somehow, the sorting on x-axis was being done by the number of installations.

**Comment by cjones051073** [comment]
When will this fix hit the main deployment btw ? I still see the issue at e.g. 

https://ports.macports.org/port/clang-8.0/stats?days=30&days_ago=0
