### ISSUE TITLE
Fix the behaviour of the back button after clicking a port from search results

### ISSUE THREAD

**Issue by umeshksingla** [macports/macports-webapp#113]
At the moment, if you click a port as a result from a search and try to go back, you need to search again. 

~~It is easy to command-click a link and it opens in a new tab but since most of the search engines provide a way to go back and access the previously returned results, I think that would be nice to have.~~

(Note: Edited by @mojca to change the request to open search results in a new window into a request to make the back button work correctly.)

**Comment by neverpanic** [comment]
Ugh, please no. I hate it when websites think they need to make the decision whether I want to open something in a new tab for me. I am perfectly capable of making this decision myself.

Instead, we could update the search functionality to include the search term in the history. Modern JavaScript is able to do that, which would make the back button behave as you'd expect it to.

**Comment by mojca** [comment]
I agree with Clemens on this.

**Comment by arjunsalyan** [comment]
The back button behaviour seems to be inconsistent across browsers, on Safari I do get the search results back but Chrome needs me to search again.

In all, searching needs some big improvements, I am on it.

**Comment by neverpanic** [comment]
Just to clarify, I'm talking about https://developer.mozilla.org/en-US/docs/Web/API/History_API/Working_with_the_History_API. We should probably use replaceState() to put the entered search term into the history (e.g. a query parameter in the URL) so that clicking back does always preserve the search term.

**Comment by mojca** [comment]
I believe that this has been fixed with the new version of the app.
In case I'm wrong, please reopen the ticket.
