### ISSUE TITLE
Proposal: drop dependency on Google Charts

### ISSUE THREAD

**Issue by l2dy** [macports/macports-webapp#114]
https://github.com/macports/macports-webapp/blob/b753285bca2771cb8bb873e0030345df3defeab8/app/ports/templates/ports/portdetail.html#L9

As stated in the [Google Charts FAQ](https://developers.google.com/chart/interactive/faq), their ToS disallows "offline" usage. Which has the following effects:
1. This website has a hard dependency on Google, and must adapt if they made backwards incompatible changes.
2. Visits to these pages could be tracked by Google.
3. In certain restricted networks where Google's APIs are unavailable, some pages would be unusable.

**Comment by mojca** [comment]
It's a pitty that this wasn't brought to attention slightly earlier as we could use a different api from the start.

I assume you saw it blocked yourself?

Which graphing tool would you suggest to use. There are plenty easy to use libraries around, I don't have much experience with either.

**Comment by l2dy** [comment]
[D3](https://github.com/d3/d3) is a very powerful JavaScript library for visualizing data. We could use a charting library based on it, e.g. [c3](https://github.com/c3js/c3) or [plotly.js](https://github.com/plotly/plotly.js).

**Comment by umeshksingla** [comment]
[HIghCharts](https://www.highcharts.com/) is an excellent alternative, I'd like if you can take a look at its [Non-Commercial FAQ](https://shop.highsoft.com/faq#Non-Commercial-0) because I did not get it fully. It allows [downloading the scripts](https://www.highcharts.com/blog/download/) for offline usage.

**Comment by umeshksingla** [comment]
> [D3](https://github.com/d3/d3) is a very powerful JavaScript library for visualizing data. We could use a charting library based on it, e.g. [c3](https://github.com/c3js/c3) or [plotly.js](https://github.com/plotly/plotly.js).

Yes, this. I have definitely heard about it a lot but have no experience with it.

**Comment by l2dy** [comment]
> [HIghCharts](https://www.highcharts.com/) is an excellent alternative, I'd like if you can take a look at its [Non-Commercial FAQ](https://shop.highsoft.com/faq#Non-Commercial-0) because I did not get it fully. It allows [downloading the scripts](https://www.highcharts.com/blog/download/) for offline usage.

"The license allows for up to 5 developers to work on our software."

Nope, don't use this.

---

TBH, I prefer depending on open source software only. And slightly OT, we should add a LICENSE file to this repository.

**Comment by mojca** [comment]
> And slightly OT, we should add a LICENSE file to this repository.

Oh, thanks for pointing this out.
@arjunsalyan, @umeshksingla: would any of you object the MIT licence?

**Comment by arjunsalyan** [comment]
> > And slightly OT, we should add a LICENSE file to this repository.
> 
> Oh, thanks for pointing this out.
> @arjunsalyan, @umeshksingla: would any of you object the MIT licence?

I don't have enough knowledge about these to speak anything, I will go by your decision.

**Comment by arjunsalyan** [comment]
> [D3](https://github.com/d3/d3) is a very powerful JavaScript library for visualizing data. We could use a charting library based on it, e.g. [c3](https://github.com/c3js/c3) or [plotly.js](https://github.com/plotly/plotly.js).

Thank you, I will check both and try to switch as soon as I can.

**Comment by arjunsalyan** [comment]
I have started incorporating [Chart.js](https://www.chartjs.org/) just because I found it more popular, but the switch would be easy now due to other changes that were made.

Do you recommend c3 or plotly.js over Chart.js?

**Comment by l2dy** [comment]
I have no preference on this. Go ahead if it doesn't require loading external resources (i.e. can be bundled into our website).

**Comment by mojca** [comment]
@arjunsalyan: this one can be closed, right?

**Comment by arjunsalyan** [comment]
Yes, this can be closed. Everything the website uses has been bundled with it.
