### ISSUE TITLE
Incorrect ‘most installed version’ is reported.

### ISSUE THREAD

**Issue by cjones051073** [macports/macports-webapp#123]
Each port seems to give ‘user(s)’ as the most installed version.... see e.g.

https://ports.macports.org/port/clang-8.0/stats?days=30&days_ago=0

**Comment by mojca** [comment]
Like this:
![image](https://user-images.githubusercontent.com/15606/65744815-de25ab80-e0f9-11e9-84bd-9c44548aa296.png)

Maybe we should create a function to return this data for a given port, and also create unit tests for it. Just as a thought.

(@arjunsalyan: we need anchors to be able to reference individual graphs. It took me a while to notice what this was referencing as I was only staring at graphs.)
