### ISSUE TITLE
Trac ticket sorting order appears to be not well defined.

### ISSUE THREAD

**Issue by cjones051073** [macports/macports-webapp#131]
See e.g.

https://ports.macports.org/port/MacVim/tickets

not obvious what sorting, if any, is used on the tickets.

My suggestion would be to simply sort on the ticket number, so oldest (newest?) first, newest (oldest?) last.

**Comment by pmetzger** [comment]
Yah, numerical order seems sanest to me, too. Oldest at top, newest at bottom.

**Comment by mojca** [comment]
I would argue the reverse and put the newest on top.

**Comment by pmetzger** [comment]
One could always allow the user to pick by clicking on the column, or not, but either way, numerical order, either forward or reverse, is saner.

**Comment by cjones051073** [comment]
@arjunsalyan @mojca may I ask id there is any intention to look into this issue at all ?

**Comment by arjunsalyan** [comment]
We are working on a major code refactoring and wish to resolve all the issues with the newer code. But it is not clear as to when we will be ready with that, so for the time being I have submitted this simple fix.

The newer order will be this:
![Screenshot 2020-04-30 at 6 28 16 PM](https://user-images.githubusercontent.com/40331563/80712981-5fba3d80-8b10-11ea-9e49-87e9c7aae342.png)
