### ISSUE TITLE
Don't open links in a new tab/window

### ISSUE THREAD

**Issue by ryandesign** [macports/macports-webapp#136]
Seems like many of the links are programmed to open in a new tab/window. Would be better if it did not do that. I can open a link into a new tab/window by holding down the Command key while clicking it if I want that, but I don't know of a way to prevent a link that is programmed to open into a new tab/window from doing that.

**Comment by cjones051073** [comment]
I second this. Its a choice that should not be forced from the server side, but left to the user to decide.

**Comment by mojca** [comment]
Most of the links are internal, but build results open in a new window.

I see 8 instances of `<a target="_blank"` in the sources. Should we simply remove all occurencies of `target="_blank"`, independent of whether it's an external or internal link?

It's easy to do, I'm just asking for some confirmation before attempting to do anything.

**Comment by cjones051073** [comment]
> Most of the links are internal, but build results open in a new window.
> 
> I see 8 instances of `<a target="_blank"` in the sources. Should we simply remove all occurencies of `target="_blank"`, independent of whether it's an external or internal link?
> 
> It's easy to do, I'm just asking for some confirmation before attempting to do anything.

For me, yes, remove them. It should be up to the reader if they want the link in the same tab, a new tab or a new window, with the last two trivially available with a right click on the link.

**Comment by mojca** [comment]
OK, thanks.

I have a trivial PR ready, I'll just wait a bit longer for Arjun's blessing before merging.

@ryandesign: slightly (un)related: there are tons of broken links to buildbot build logs. I'll open a new ticket for that, but I guess that we need to add another field to check whether a particular build is still accessible via web interface, and only make a hyperlink if that log still exists. I guess that it's no longer relevant which build number it was in case it's no longer accessible, and we don't care if we don't show that number to the user, right? Any further thoughts about that topic?
