### ISSUE TITLE
Show distribution of macOS version on statistics page

### ISSUE THREAD

**Issue by mojca** [macports/macports-webapp#14]
As the first step before implementing anything more complex, it could be a nice exercise to show the distribution of macOS versions among the users who submitted the statistics:
* show the distribution of macOS version for users who made the submission in the last 4 weeks (among all the users who made the submission in the last 4 weeks, pick the latest submission from each user and count how many users have which OS version)
* the same, but for all-time submissions.

This could be shown on [statistics/](https://frozen-falls-98471.herokuapp.com/statistics/), either using a table or a chart. The important part would be an efficient database call.

This is planned for Week 5, but if you get bored with other tasks, this is something you could play with to demonstrate what you learned in the database course :)

**Comment by arjunsalyan** [comment]
This has been completed.
