### ISSUE TITLE
Shorten port page's canonical URL

### ISSUE THREAD

**Issue by ryandesign** [macports/macports-webapp#142]
Currently the URL of a port's main (summary) page is e.g.

`https://ports.macports.org/port/reflex/summary`

I would like the canonical URL of a port's web page -- the one we might be asking developers to add on their web sites to link back to us -- to be as short and sweet as possible. I'd certainly remove the `/summary` part:

`https://ports.macports.org/port/reflex`

I might even remove the `/port` part:

`https://ports.macports.org/reflex`

Or maybe not; if we integrate the web app into the main web site e.g. via CDN rules, it would be fine to have just:

`https://macports.org/port/reflex`

**Comment by mojca** [comment]
The `summary` part has gone now. We now provide two options
```
https://ports.macports.org/port/reflex
https://ports.macports.org/port/reflex/details
```

Removing the `port/` part is not feasible at the moment as we also need other functionality like `statistics/` and we'll run into troubles if someone decides to package a port with that name.

I'm all in favour of merging the contents of other parts of the page into the same uniform web application, but until we do that, I don't see what we could do to shorten the url.
