### ISSUE TITLE
Add installation instructions to each port page

### ISSUE THREAD

**Issue by ryandesign** [macports/macports-webapp#144]
Each port page should have simple instructions for installing the port. I had something like this in my earlier attempt at a MacPorts web app from 2014, at the bottom of the righthand column. For installable ports, it would say something like this:

> To install ImageMagick on macOS, [install MacPorts](https://www.macports.org/install.php), then open Terminal (in Applications › Utilities) and run:
> ```
> sudo port install ImageMagick
> ```
> To see what files were installed by ImageMagick, run:
> ```
> port contents ImageMagick
> ```
> To later upgrade ImageMagick, run:
> ```
> sudo port selfupdate
> sudo port upgrade ImageMagick
> ```

For ports that are not installable (i.e. obsolete ports), it would say something different. For example:

> This port is not meant to be installed. It has been replaced by [the other port's name](https://ports.macports.org/port/theOtherPortsName).

Note that not all obsolete ports declare a replacement; some are just obsolete with no alternative available; in that case, the second sentence would not be printed.

In any case, I also printed uninstallation instructions:

> To uninstall ImageMagick, run:
> ```
> sudo port uninstall ImageMagick
> ```

Those basics should get the user on the right track. It could end with something like:

> To learn more about using MacPorts, read the [MacPorts Guide](https://guide.macports.org).

This could all be in smaller text and wouldn't have to be the main focus of the page, but I think having it *somewhere* on each port's page would be a great help to new users, both those who have already landed on the page and those who are just seeing snippets of it from their search engine results.

We need to remember that users who find these pages via search engines, or perhaps from developers' web sites, have not necessarily heard of MacPorts before and don't know how to use it.

We've already had one user saying they found the webapp page for a port they wanted to install, but then "couldn't find the download button". They contacted us and we were able to help orient them, which is great, but it would have saved them and us time if they had found the information right there on the page. I also worry that for each person who takes the time to try to contact us, there are others who give up and leave.

New users also really don't want to have to wade through the full Guide at this point. They just want to install the port quickly, and once they see that that works, then they might check out further documentation.

**Comment by mojca** [comment]
@ryandesign: most of your suggestions have been addressed. Can you please take another look at the new site and suggest what else to change, so that we could close this ticket in a satisfactory way?

**Comment by harens** [comment]
I was just searching up `Janet MacPorts` (the programming language) on Startpage, and surprisingly, the first result came from this website: https://techindyeah.org/

I've seen a few MacPorts website mock-ups before, but this one has some of @ryandesign's suggestions (although not the obsolete one, which is already available), and so it reminded me of this issue. I couldn't find who made the website though.

By the way, it goes without saying but thank you @mojca and @arjunsalyan for maintaining the amazing website! :)

**Comment by arjunsalyan** [comment]
> I was just searching up `Janet MacPorts` (the programming language) on Startpage, and surprisingly, the first result came from this website: https://techindyeah.org/
> 

This is the new version of the website which I am currently hosting at https://server1.arjunsalyan.com/. We worked on it last year. The code is hosted in the `gsoc2020` branch of this repository. https://techindyeah.org is just a redirect to my server.

We are in the process of transitioning to the new version of the website. Soon ports.macports.org will run the version from my server.

**Comment by mojca** [comment]
@arjunsalyan: now that the page was officially deployed, it probably makes sense to ensure that alternative links don't end up circulating around as "look, here I found page X explaining how to install port Y" as in the above example of `techindyeah.org`, and in particular not as the first google hit (before the official page). Either a redirect or alternative contents would probably make sense.

Other than that I would be inclined to close the ticket since Ryan's suggestion has basically been implemented. Further improvements may be suggested via new tickets or pull requests.
