### ISSUE TITLE
Swap placement of long description and port health

### ISSUE THREAD

**Issue by ryandesign** [macports/macports-webapp#146]
Currently, port pages have the port health at the top (below the short description) and off in the righthand column is the long description. I would switch the position of these two elements.

I would make the short description text larger, for example using the Twitter Bootstrap `lead` class, to differentiate it from the long description which would then be below it.

Because some port's long descriptions can be very long, I would limit the height of the long description div to some reasonable number of rows; if the content overflows, show a "more..." link that can reveal the full long description.

In their new place in the righthand column, I would reformat the port health indicators vertically, with the same [green check](https://octicons.github.com/icon/check) / [red x](https://octicons.github.com/icon/x) icons GitHub uses to decorate commits, perhaps with OS names like this:

![port-health-mockup](https://user-images.githubusercontent.com/429209/69860223-60962d00-125b-11ea-9ddf-78a905cf43d2.png)

**Comment by arjunsalyan** [comment]
I have tried to incorporate these changes. Here is the URL of the temporary deployment: http://macports.silentfox.tech/port/slowhttptest/.

**Comment by mojca** [comment]
@ryandesign: do you have any further suggestions for improvements or can we close this now (based on what's on the temporary repo)?

**Comment by mojca** [comment]
I'm closing this ticket for now since the design has undergone some major changes anyway (and includes your suggestions).
If you have further suggestions about the new site (offline at the moment), please simply file a new ticket. Thanks.
