### ISSUE TITLE
About page references old Subversion repository

### ISSUE THREAD

**Issue by ryandesign** [macports/macports-webapp#147]
The about page says:

> The source of the [mpstats] client is currently available at /trunk/dports/sysutils/mpstats in the MacPorts Subversion repository

But we imported everything from Subversion to GitHub at the end of 2016, and the link is actually to https://github.com/macports/macports-ports/tree/master/sysutils/mpstats, so it seems the text here needs to be updated.

**Comment by mojca** [comment]
There are two links to subversion, one of them pointing to https://trac.macports.org/browser/branches/gsoc11-statistics which incidentally doesn't redirect, but can be found at an utterly unexpected location: https://github.com/macports/macports-contrib/tree/gsoc11-statistics/.

I can fix the link to ports, but I'm not sure if that strange location in the contrib repository actually deserves an explicit link. What we could do is create a new repository out of that branch and immediately explicitly archive it. Thoughts?

**Comment by mojca** [comment]
The relevant code is [here](https://github.com/macports/macports-webapp/blob/8da0f1adad9b37ba481934fa90ba3763738a666a/app/ports/templates/ports/about.html#L81).

We are actually already providing a link to `mpstats` in the same paragraph, so my suggestion would rather be to simply remove the whole sentence?

**Comment by ryandesign** [comment]
Ok
