### ISSUE TITLE
Copyable search URL

### ISSUE THREAD

**Issue by ryandesign** [macports/macports-webapp#149]
When I type into the search box, a search automatically happens without pressing Return, however even if I do press Return, the URL doesn't change. This makes it impossible to copy and paste the URL of the search results, which I might want to do for example in reply to a message on the mailing list where someone has asked if we have a particular port.

**Comment by arjunsalyan** [comment]
I had started work on a separate and more advanced search page but could not take it forward. I think the search on home should be left as it is- just a quick way to discover ports. And an advanced version could shift to a separate page.
