### ISSUE TITLE
Add number of trac tickets

### ISSUE THREAD

**Issue by mojca** [macports/macports-webapp#19]
A potentially useful information would be the number of trac tickets, so that the `Trac Tickets` tab would read `Trac Tickets (3)` instead and immediately give us a sense of the potential number of issues.

Or, alternatively, something like `Trac Tickets (5f, 2b)` meaning that there are 5 feature requests and 2 bug reports. I believe we have:
* feature requests
* bug reports
* update requests (when a port is outdated)

Note that this is a super low priority thing and would add a tiny bit to the required time to load the page. If implemented, maybe that value should be cached for a while. There is absolutely no hurry to implement it, if done at all.

**Comment by arjunsalyan** [comment]
I have mostly taken care of it by showing the count of tickets in the tab-button. I have also added ticket-id for the tickets. Thank you

**Comment by mojca** [comment]
Thank you very much, I'm happy.
The tab with tickets makes more sense now and the number is useful as well.

Unrelated to this ticket I would say that there is no need for using the yellow colour for "No tickets found".

There is also no need to use yellow for the tickets count. Some shade of gray might be fine, even though you now gave me a new idea (with super super low priority). We could use red colour for bugs and yellow for updates, while feature requests don't need a colour that sticks out.

**Comment by arjunsalyan** [comment]
> * feature requests
> * bug reports
> * update requests (when a port is outdated)

Looking at this: https://trac.macports.org/query?status=!closed&port=~perl5.28 . Do I need to pick the `type` column? It here says `defect` for all tickets.

**Comment by mojca** [comment]
> Looking at this: https://trac.macports.org/query?status=!closed&port=~perl5.28 . Do I need to pick the `type` column? It here says `defect` for all tickets.

Yes.

**Comment by mojca** [comment]
I consider this done, thank you very much.
