### ISSUE TITLE
Optimise Updates from Portindex

### ISSUE THREAD

**Issue by mojca** [macports/macports-webapp#2]
We would ideally update the app in two different ways:
* After "each" git commit. (Probably triggered from either github or from an action in buildbot?)
* Once per day from the latest portindex (to ensure that we catch up even if some network connectivity went down in the meantime, or if there were some strange bugs with update procedure etc.).

We would start with a reliable way to update all ports from full portindex.

The code should be accompanies by unit test(s) containing:
* a set of ports before the update
* a set of ports after update
* some way (a script?) that runs `portindex` followed by `portindex2json` for both the old and the new set (directory)
* the test should first import the old json, then run the update with the new json file with port data, and make a set of test confirming that we achieved the desired functionality:
  * check that version gets updated in some ports
  * check that maintainers get added
  * check that maintainers get removed
  * check that categories get updated (added or removed): test the number of ports belonging to each category
  * declare some ports obsolete in the new set and make sure that you get the desired functionality
  * remove some regular ports and make sure everything works correctly
  * remove some obsolete ports in the new set and test for correct functionality

We can start experimenting with incremental updates, but the idea about the best update strategy might still change after some brainstorming etc., so I would not spend too much effort on that part.

**Comment by arjunsalyan** [comment]
Updates have also been fixed.
