### ISSUE TITLE
Provide basic API with information about ports

### ISSUE THREAD

**Issue by mojca** [macports/macports-webapp#21]
We would need a "complete" API with the information about ports at some point, but having something basic now would also help other projects, in particular @rajdeepbharati's buildbot views (feel free to provide feedback about what is needed).

I assume that something to start with could be for example
```
https://webapp.macports.org/api/v1/port/{portname}
```
as per your specification in the proposal, but I don't care if we don't yet provide all the fields immediately. 

Of course the first part of the url would still be the temporary one.

Maybe @rajdeepbharati would also benefit from the full list of active ports?

**Comment by rajgoesout** [comment]
A web api with the following endpoints would help my project:

#### - `GET /ports`
#### - `GET /port/portname` 
(with the details like maintainer, etc.) example:
```json
{
    "portdir"          : "python\/ansible_select",
    "description"      : "Common files for selecting the default Ansible version",
    "homepage"         : "https:\/\/www.macports.org\/",
    "epoch"            : "0",
    "platforms"        : "darwin",
    "name"             : "ansible_select",
    "closedmaintainer" : true,
    "license"          : "BSD",
    "maintainers"      : [{
        "email"  : {
            "domain" : "macports.org",
            "name"   : "adfernandes"
        },
        "github" : "adfernandes"
    },{
        "email"  : {
            "domain" : "macports.org",
            "name"   : "blair"
        },
        "github" : "blair"
    },{
        "email"  : {
            "domain" : "gmail.com",
            "name"   : "pedro.salgado"
        },
        "github" : "steenzout"
    }],
    "long_description" : "This port installs files that allow 'port select' to create links to the preferred default version of Ansible.",
    "version"          : "0.1",
    "categories"       : ["sysutils"],
    "revision"         : "0",
    "builds"           : []
}
```
#### - `GET /port/portname/builds`
(list of builds for each port) similar to https://buildbot.buildbot.net/api/v2/builds?property=*

Thanks.

**Comment by arjunsalyan** [comment]
Thank you, I will take it up ASAP.

> A web api with the following endpoints would help my project:
> 
> #### - `GET /ports`

What do you expect in return with this- all ports or ports under a category?

**Comment by rajgoesout** [comment]
> What do you expect in return with this- all ports or ports under a category?

It may be all ports or category based, whichever is convenient for you. (I guess all ports will make the api slow)
Also, there should be build information in /port/portname/builds, as in your webapp https://frozen-falls-98471.herokuapp.com/port/py37-tensorflow/

**Comment by arjunsalyan** [comment]
I have made the API to fetch port-info active. Please see this: http://frozen-falls-98471.herokuapp.com/api/v1/port/faust/

**GET <site_url>/api/v1/port/{port-name}**

It will currently give you the following info:
- name
- portdir
- categories
- maintainers
- version
- variants

Let me know if you need any other property. I will add other APIs very soon. Thanks

**Comment by rajgoesout** [comment]
This is great.
Could you enable CORS (since I am blocked from accessing https://frozen-falls-98471.herokuapp.com/ from the frontend)
Maybe you can use django-cors-headers

**Comment by arjunsalyan** [comment]
Ok. Which origins do you need it to be enabled for?

**Comment by rajgoesout** [comment]
http://localhost:8010/

**Comment by arjunsalyan** [comment]
Please try now, I have enabled CORS for 'GET' method at '/api/*' from localhost:8010.

**Comment by arjunsalyan** [comment]
I have also enabled build history at:

**GET /api/v1/port/{port-name}/builds**

Example: http://frozen-falls-98471.herokuapp.com/api/v1/port/perl5.28/builds

**Comment by rajgoesout** [comment]
Thank you. Is it possible to also pass the `results` value?
http://docs.buildbot.net/0.8.12/developer/results.html?highlight=results#module-buildbot.status.results

**Comment by arjunsalyan** [comment]
We probably do not have `results` in the database yet.

**Comment by arjunsalyan** [comment]
> It may be all ports or category based, whichever is convenient for you. (I guess all ports will make the api slow)

Even some categories have as much as 6750 ports. Either way, the API is going to be slow due to system limitations on the demo app.

#### -`GET /api/v1/category/{category-name}/ports/` 
should return you a list of JSON objects containing only the names of ports in that category.

Please let me know if you need some changes with this.

**Comment by rajgoesout** [comment]
> Even some categories have as much as 6750 ports. Either way, the API is going to be slow due to system limitations on the demo app.

Okay, then it would be nice to have an api with the list of ports (not grouped by category)

**Comment by mojca** [comment]
Thanks a lot for implementing this.

I guess that the best way to serve names of N thousand ports is by only returning them in chunks of 100 (or any specified number of ports, with the maximum being specified somewhere, for example 100 or 1000). It's the same as what pagination does. I imagine that retrieving just names of ports should be relatively fast anyway, as long as you make sure that django isn't fetching the whole lot of extra information about ports (like potentially all columns like descriptions etc. + all relations).

One function that api should support is return the total number of ports, to start with, and when you ask for ports, api could support both:
* queries telling which port number to start with (in alphabetical order)
* or the first few letters of the port (or rather: any port that is alphabetically >= than the specified string)

Results could make sense. I guess the reason why I didn't think of it is because I personally don't really care about exceptions in builds, as that's not telling me any useful information about whether a port is working or broken, it just tells me that the infrastructure was broken at the time when the build was run. On the other hand what I miss in @rajdeepbharati's views (or any other buildbot view, for that matter), is some further colour-coding of which step failed. The web app currently stores the info about whether port build or build of dependencies failed. In other situations (say, for macports base builds) it could be useful to know if software build or unit tests failed. But that's a general feature request for the buildbot itself.

If @rajdeepbharati finds the status useful, it can be added. As a quick workaround you could also ask buildbot directly in another json call after you read the build number. I definitely wrote down other info that we would like to add to the build history (like port version etc.), but I need to find where this is.

**Comment by rajgoesout** [comment]
> On the other hand what I miss in @rajdeepbharati's views (or any other buildbot view, for that matter), is some further colour-coding of which step failed. 

The view has a link to the build, where you can see the step which failed. For example: https://buildbot.buildbot.net/#/builders/6/builds/773

Further color-coding may be done for steps (that would be custom, and depend on macports steps). OTOH the error message could be shown in the view, but then it might occupy too much space.

**Comment by arjunsalyan** [comment]
I have added two more API calls:

#### `GET /api/v1/ports/count/`
It would return a JSON object with `count` and `time`.

#### `GET /api/v1/ports/{{page_size}}/page/{{page_num}}`/
`page_size` (int) is to adjust the size of chunks, and `page_num` (int) lets you paginate over the chunks. Ports are ordered alphabetically.

Example: `page_size = 1000` and `page_num = 1` returns ports from 0 to 999 when ordered alphabetically.
http://frozen-falls-98471.herokuapp.com/api/v1/ports/1000/page/1/

**EDIT**: It takes me 4.5 seconds to fetch names of all ports `page_size = 23000`. It is quite decent.

**Comment by rajgoesout** [comment]
Thanks!

**Comment by arjunsalyan** [comment]
Please let me know if you need more data from the app.

**Comment by mojca** [comment]
API is relatively complete in the `gsoc2020` branch and nicely referenced, so I guess this ticket can be closed.
