### ISSUE TITLE
Build stats. pages hang whilst loading.

### ISSUE THREAD

**Issue by cjones051073** [macports/macports-webapp#216]
See this for a number of ports. build stats. page just hangs with the spinning waiting symbol. see e.g.

https://ports.macports.org/port/libgcc10/stats?days=30&days_ago=0

**Comment by arjunsalyan** [comment]
We use `distutils.version.LooseVersion` to sort the versions of the ports. But it fails with an error `TypeError : '<' not supported between instances of 'str' and 'int'` whenever it encounters an underscore or a hyphen in the version string. I had fixed this by pre-cleaning the versions before sorting and converting underscores to dots. Same needs to be done with hyphens as I can see that `libgcc10` had a version `10.1.0-RC-20200430_0`.

**Comment by jmroot** [comment]
I have a feeling you're going to be chasing bugs here endlessly unless you use the exact same version comparison algorithm as MacPorts base.
