### ISSUE TITLE
Indicate combinations of licenses more clearly

### ISSUE THREAD

**Issue by ryandesign** [macports/macports-webapp#234]
The web app currently appears to list a port's license exactly as it's written in the Portfile, but the notation we use doesn't make completely clear what we mean when multiple licenses are listed.

For example the py-setuptools portfile currently says:

> `license MIT {PSF ZPL} {Apache-2 BSD}`

The web app currently displays:

> License: MIT {PSF ZPL} {Apache-2 BSD}

But `port info py-setuptools` is more clear: it says:

> License: MIT and (PSF or ZPL) and (Apache-2 or BSD)

In other words, someone wanting to use this software must comply with the MIT license, and their choice of either the PSF or ZPL licenses, and their choice of either the Apache-2 or BSD licenses.

The web app should probably adopt the same wording as shown in `port info`, for consistency and clarity.

**Comment by arjunsalyan** [comment]
Duplicate of https://github.com/macports/macports-webapp/issues/44

**Comment by arjunsalyan** [comment]
The changes will be visible only for those ports which get new commits. To update license on all ports, a full database update is needed which should be done soon.

However, on the temporary testing website, the changes can be seen immediately: http://macports.silentfox.tech/port/py-setuptools/details/
