### ISSUE TITLE
Refactor code in load and update in Port model

### ISSUE THREAD

**Issue by umeshksingla** [macports/macports-webapp#24]
Thread: https://github.com/macports/macports-webapp/pull/13/files#r298804614

I don't particularly like code duplication either, and I'm still confused about the amount of time it takes to populate our database, but as long as we have such a huge gap between update and efficient data store, I don't mind if we keep an efficient method in. Just make sure that it's properly and extensively backed by unit tests. (The number of unit tests is relatively small compared to the amount of code we have so far.)

_Originally posted by @mojca in https://github.com/macports/macports-webapp/pull/13_

**Comment by mojca** [comment]
This has been handled.
