### ISSUE TITLE
Get rid of fixed versions for requirements

### ISSUE THREAD

**Issue by umeshksingla** [macports/macports-webapp#25]
This comment is not specific to any particular line, but eventually I would like to get rid of so stringent requirements. I would only specify some limitations when there's a known incompatibility and an older version is needed.

With unit tests we should always be testing against the latest version from pypi, so that one can immediately notice if something gets broken and needs fixing for compatibility, else we might end up having troubles as time passes by. Maybe we need to document what version of dependencies was last used & well tested, but I would like to avoid sticking with an ever increasing age of django, for example.

_Originally posted by @mojca in https://github.com/macports/macports-webapp/pull/13_

**Comment by mojca** [comment]
@neverpanic: what do you suggest?

It looks like two somewhat orthogonal goals. One would be the ability to run unit tests against the latest version of everything and quickly figure out if something is broken with newer version(s) of dependencies. The other one is having a reproducible docker image.

So I'm not sure on which of the sides I stand at the moment, or rather how to quickly achieve both goals at the same time.

**Comment by neverpanic** [comment]
Isn't there a bot which could automatically open PRs updating the packages to the latest versions, say, once a week? Then we run the tests, if everything is fine, we merge and it gets deployed.

**Comment by mojca** [comment]
OK, well, I guess that's good enough.
I've seen the bot submit the PR #71, so I assume you set it up already?
I did not change major versions, only minor ones, but well ...
