### ISSUE TITLE
Django debug is enabled on live MacPorts site

### ISSUE THREAD

**Issue by tux-o-matic** [macports/macports-webapp#253]
I just faced a Django stack trace debug page on ports.macports.org, looking at [settings.py](https://github.com/macports/macports-webapp/blob/5ca11c03418bc4b95b1616caa40f4c4dd8e33164/app/MacPorts/settings.py#L27) I can see that Django debug value is set to true and seems to be kept as is in the live site.

**Comment by arjunsalyan** [comment]
Thank you, this was fixed in https://github.com/macports/macports-webapp/commit/c74730ea00b32958b00ef3ce9b745ddf1c6795f6
