### ISSUE TITLE
Add macOS 11.0 builders

### ISSUE THREAD

**Issue by jmroot** [macports/macports-webapp#258]
ports-11.0_x86_64 is already online and ports-11.0_arm64 is configured but not yet active.

**Comment by ryandesign** [comment]
ports-11.0_arm64 is now active as well. I see that both of them have been added to the web site.

Can they please be renamed from "11.0" to "11"? I've just made that change on buildbot itself so perhaps the app needs to be updated in how it gets the data from buildbot.

Old URLs to "11.0" will continue to work so if you have complete URLs to "11.0" build logs stored in the database there's no need to update them.

**Comment by neverpanic** [comment]
Done.
