### ISSUE TITLE
Use GET request format for optional parameters like `page`

### ISSUE THREAD

**Issue by umeshksingla** [macports/macports-webapp#26]
This API call sounds a bit strange to me (I wanted to comment immediately, and didn't / forgot). I'm not sure what the best way would be. Web sites would use a question mark with optional parameters after it, but I'm not sure if that's also the usual way for such API.

If I look at GitHub's own API:
https://developer.github.com/v3/repos/commits/#list-commits-on-a-repository
they do seem to use question marks in this exact way:
```
https://api.github.com/resource?page=2
```
Maybe something like
```
ports/list?count=100&page=3
```
or
```
# meaning to start with the first port that's alphabetically >= as `pe` (could be perl5)
ports/list?count=30&start_with=pe
```

_Originally posted by @mojca in https://github.com/macports/macports-webapp/pull/13_

**Comment by mojca** [comment]
This seems to work already: `api/v1/ports/?page=3`
