### ISSUE TITLE
Fonts missing on Freeciv on 10.5.8 powerpc

### ISSUE THREAD

**Issue by smnbldwn** [macports/macports-webapp#264]
![Picture 1](https://user-images.githubusercontent.com/8080349/111029095-acd69380-83f2-11eb-8517-d14adc82276e.png)
I used Macports to install Freeciv on my Powerbook running 10.5.8. It compiled and installed all the dependencies and then Freeciv without error messages. When I opened Freeciv, it started but there is no text and where there should be text, it is just placeholders. Do I need to install a missing font?

**Comment by kencu** [comment]
First of all, welcome! This particular place is not a great place to report bugs, I'm afraid, as nobody would come here usually to look for them.

Something is not right, you're certainly correct. A missing font sounds like a reasonable place to start looking for what is wrong, indeed.

Please go here <https://trac.macports.org> to report your bug, which is where everyone will be expecting to find it. 

you can still reference this image if you like. Trac is not quite as great at images as github issues is, but you can link to them or you can upload them as attachments.

By the way, you might be interested in SDL2 for PowerPC here https://github.com/kencu/LeopardPorts/tree/master/devel/libsdl2 which some interested parties have worked on. It allows quite a bit (not all) SDL2 software to work on Tiger and Leopard PPC.

It's not in MacPorts as yet, for various reasons.

**Comment by smnbldwn** [comment]
Thank you, will do.
