### ISSUE TITLE
Only 10.15 builds are being imported into web app

### ISSUE THREAD

**Issue by ryandesign** [macports/macports-webapp#273]
I am curious why the web app only shows build information for one build (on 10.15) for this port:

https://ports.macports.org/port/lexbor/summary

Builds were successful on all OS versions. This is a new port that no other port depends on, so its build information should have been readily available as a separate build on all OS versions.

See commit status on this commit: https://github.com/macports/macports-ports/commit/b5b22439d06dc135b77031083933bd5962b9cc93

**Comment by ryandesign** [comment]
It looks like only build information for 10.15 is being imported, for all ports:

https://ports.macports.org/ports/all_builds/

Any idea why?

**Comment by neverpanic** [comment]
We're at least not getting any error messages from the cronjob. Anything else I'll have to investigate first :/

**Comment by ryandesign** [comment]
According to the build server web logs, Braeburn continues to retrieve build information for all platforms, e.g.:
```
136.243.18.213 - - [19/Apr/2021:20:50:03 +0000] "GET /json/builders/ports-10.11_x86_64-builder/builds/-1 HTTP/1.1" 200 7176 "-" "Python-urllib/3.8" "-"
136.243.18.213 - - [19/Apr/2021:20:50:04 +0000] "GET /json/builders/ports-10.11_x86_64-builder/builds/134087 HTTP/1.1" 404 153 "-" "Python-urllib/3.8" "-"
136.243.18.213 - - [19/Apr/2021:20:50:05 +0000] "GET /json/builders/ports-10.12_x86_64-builder/builds/-1 HTTP/1.1" 200 7175 "-" "Python-urllib/3.8" "-"
136.243.18.213 - - [19/Apr/2021:20:50:06 +0000] "GET /json/builders/ports-10.12_x86_64-builder/builds/139159 HTTP/1.1" 404 153 "-" "Python-urllib/3.8" "-"
136.243.18.213 - - [19/Apr/2021:20:50:07 +0000] "GET /json/builders/ports-10.13_x86_64-builder/builds/-1 HTTP/1.1" 200 6328 "-" "Python-urllib/3.8" "-"
136.243.18.213 - - [19/Apr/2021:20:50:08 +0000] "GET /json/builders/ports-10.13_x86_64-builder/builds/103815 HTTP/1.1" 404 153 "-" "Python-urllib/3.8" "-"
136.243.18.213 - - [19/Apr/2021:20:50:09 +0000] "GET /json/builders/ports-10.14_x86_64-builder/builds/-1 HTTP/1.1" 200 6305 "-" "Python-urllib/3.8" "-"
136.243.18.213 - - [19/Apr/2021:20:50:12 +0000] "GET /json/builders/ports-10.14_x86_64-builder/builds/79609 HTTP/1.1" 404 153 "-" "Python-urllib/3.8" "-"
136.243.18.213 - - [19/Apr/2021:20:50:12 +0000] "GET /json/builders/ports-10.9_x86_64-builder/builds/-1 HTTP/1.1" 200 5725 "-" "Python-urllib/3.8" "-"
136.243.18.213 - - [19/Apr/2021:20:50:14 +0000] "GET /json/builders/ports-10.9_x86_64-builder/builds/138906 HTTP/1.1" 404 153 "-" "Python-urllib/3.8" "-"
136.243.18.213 - - [19/Apr/2021:20:50:15 +0000] "GET /json/builders/ports-10.10_x86_64-builder/builds/-1 HTTP/1.1" 200 5750 "-" "Python-urllib/3.8" "-"
136.243.18.213 - - [19/Apr/2021:20:50:16 +0000] "GET /json/builders/ports-10.10_x86_64-builder/builds/135597 HTTP/1.1" 404 153 "-" "Python-urllib/3.8" "-"
136.243.18.213 - - [19/Apr/2021:20:50:17 +0000] "GET /json/builders/ports-10.8_x86_64_legacy-builder/builds/-1 HTTP/1.1" 404 153 "-" "Python-urllib/3.8" "-"
136.243.18.213 - - [19/Apr/2021:20:50:18 +0000] "GET /json/builders/ports-10.7_x86_64_legacy-builder/builds/-1 HTTP/1.1" 404 153 "-" "Python-urllib/3.8" "-"
136.243.18.213 - - [19/Apr/2021:20:50:21 +0000] "GET /json/builders/ports-10.6_x86_64_legacy-builder/builds/-1 HTTP/1.1" 404 153 "-" "Python-urllib/3.8" "-"
136.243.18.213 - - [19/Apr/2021:20:50:22 +0000] "GET /json/builders/ports-10.6_i386_legacy-builder/builds/-1 HTTP/1.1" 404 153 "-" "Python-urllib/3.8" "-"
136.243.18.213 - - [19/Apr/2021:20:50:23 +0000] "GET /json/builders/ports-10.5_ppc_legacy-builder/builds/-1 HTTP/1.1" 404 153 "-" "Python-urllib/3.8" "-"
136.243.18.213 - - [19/Apr/2021:20:50:23 +0000] "GET /json/builders/ports-10.8_x86_64-builder/builds/-1 HTTP/1.1" 200 5707 "-" "Python-urllib/3.8" "-"
136.243.18.213 - - [19/Apr/2021:20:50:26 +0000] "GET /json/builders/ports-10.8_x86_64-builder/builds/38735 HTTP/1.1" 404 153 "-" "Python-urllib/3.8" "-"
136.243.18.213 - - [19/Apr/2021:20:50:26 +0000] "GET /json/builders/ports-10.7_x86_64-builder/builds/-1 HTTP/1.1" 200 5707 "-" "Python-urllib/3.8" "-"
136.243.18.213 - - [19/Apr/2021:20:50:27 +0000] "GET /json/builders/ports-10.7_x86_64-builder/builds/44831 HTTP/1.1" 404 153 "-" "Python-urllib/3.8" "-"
136.243.18.213 - - [19/Apr/2021:20:50:29 +0000] "GET /json/builders/ports-10.6_x86_64-builder/builds/-1 HTTP/1.1" 200 5434 "-" "Python-urllib/3.8" "-"
136.243.18.213 - - [19/Apr/2021:20:50:30 +0000] "GET /json/builders/ports-10.6_x86_64-builder/builds/48749 HTTP/1.1" 404 153 "-" "Python-urllib/3.8" "-"
136.243.18.213 - - [19/Apr/2021:20:50:31 +0000] "GET /json/builders/ports-10.6_i386-builder/builds/-1 HTTP/1.1" 200 5387 "-" "Python-urllib/3.8" "-"
136.243.18.213 - - [19/Apr/2021:20:50:31 +0000] "GET /json/builders/ports-10.6_i386-builder/builds/26699 HTTP/1.1" 404 153 "-" "Python-urllib/3.8" "-"
136.243.18.213 - - [19/Apr/2021:20:50:32 +0000] "GET /json/builders/ports-10.15_x86_64-builder/builds/-1 HTTP/1.1" 200 6304 "-" "Python-urllib/3.8" "-"
136.243.18.213 - - [19/Apr/2021:20:50:33 +0000] "GET /json/builders/ports-10.15_x86_64-builder/builds/55822 HTTP/1.1" 200 7145 "-" "Python-urllib/3.8" "-"
136.243.18.213 - - [19/Apr/2021:20:50:35 +0000] "GET /json/builders/ports-10.15_x86_64-builder/builds/55823 HTTP/1.1" 200 6302 "-" "Python-urllib/3.8" "-"
136.243.18.213 - - [19/Apr/2021:20:50:36 +0000] "GET /json/builders/ports-10.15_x86_64-builder/builds/55824 HTTP/1.1" 200 6304 "-" "Python-urllib/3.8" "-"
136.243.18.213 - - [19/Apr/2021:20:50:36 +0000] "GET /json/builders/ports-10.15_x86_64-builder/builds/55825 HTTP/1.1" 200 6305 "-" "Python-urllib/3.8" "-"
136.243.18.213 - - [19/Apr/2021:20:50:37 +0000] "GET /json/builders/ports-10.15_x86_64-builder/builds/55826 HTTP/1.1" 200 6305 "-" "Python-urllib/3.8" "-"
136.243.18.213 - - [19/Apr/2021:20:50:38 +0000] "GET /json/builders/ports-11_x86_64-builder/builds/-1 HTTP/1.1" 200 6216 "-" "Python-urllib/3.8" "-"
136.243.18.213 - - [19/Apr/2021:20:50:39 +0000] "GET /json/builders/ports-11_x86_64-builder/builds/22031 HTTP/1.1" 404 153 "-" "Python-urllib/3.8" "-"
136.243.18.213 - - [19/Apr/2021:20:50:47 +0000] "GET /json/builders/ports-11_arm64-builder/builds/-1 HTTP/1.1" 200 3475 "-" "Python-urllib/3.8" "-"
136.243.18.213 - - [19/Apr/2021:20:50:48 +0000] "GET /json/builders/ports-11_arm64-builder/builds/12498 HTTP/1.1" 404 153 "-" "Python-urllib/3.8" "-"
```

**Comment by jmroot** [comment]
Why are so many of those 404?

**Comment by ryandesign** [comment]
This is the problem I described in https://trac.macports.org/ticket/62401. After the failed buildmaster SSD was replaced, I skipped about 100 build numbers for every builder except 10.15. The import process needs to skip the ~100 nonexistent builds to get back to builds that exist.

**Comment by ryandesign** [comment]
Should this line be `continue` instead of `break`?

https://github.com/macports/macports-webapp/blob/master/app/ports/models/buildhistory.py#L117

**Comment by neverpanic** [comment]
Yeah, probably. I guess this was written with the intent to be resistant to temporary failures, but that now breaks things for permanent ones. `get_data_from_url()` should probably differentiate the temporary vs. permanent cases depending on the HTTP error code and continue on permanent errors while breaking on temporary ones.

**Comment by mojca** [comment]
When this was written, I wasn't aware that it was a valid situation to have some build numbers in-between missing (I also didn't think of the situation when the webapp would be down for so long that more than 10k builds would pass by in the meantime, which is another case of when some builds could no longer be retrieved).

In case the buildbot master temporarily becomes non-responsive or goes down while fetching the builds, we should certainly not continue, else those builds might never be imported again. 404 might be a valid case to skip the build though, but we need to clearly distinguish between the two scenarios, like @neverpanic suggested.

@arjunsalyan

**Comment by arjunsalyan** [comment]
> Should this line be `continue` instead of `break`?
> 
> https://github.com/macports/macports-webapp/blob/master/app/ports/models/buildhistory.py#L117

In case of a 404 response code we need to have continue, but for all other cases I propose that we keep break.

**Comment by mojca** [comment]
> In case of a 404 response code we need to have continue, but for all other cases I propose that we keep break.

Yes, indeed.
Are you willing to prepare a patch (and make sure that it also ends up in the new branch)?

**Comment by herbygillot** [comment]
> When this was written, I wasn't aware that it was a valid situation to have some build numbers in-between missing (I also didn't think of the situation when the webapp would be down for so long that more than 10k builds would pass by in the meantime, which is another case of when some builds could no longer be retrieved).
> 
> In case the buildbot master temporarily becomes non-responsive or goes down while fetching the builds, we should certainly not continue, else those builds might never be imported again. 404 might be a valid case to skip the build though, but we need to clearly distinguish between the two scenarios, like @neverpanic suggested.
> 
> @arjunsalyan

What is a clean way to ensure that we get the next available build, but don't end up skipping builds in case the buildbot is down?

Sounds like it would be a 404 in both cases....

**Comment by mojca** [comment]
If the buildbot is down, you should not get any response at all (so not the 404 response either).
It would either be "server not reachable" or "timeout" or something along those lines.

**Comment by ryandesign** [comment]
> What is a clean way to ensure that we get the next available build, but don't end up skipping builds in case the buildbot is down?
> 
> Sounds like it would be a 404 in both cases....

If buildmaster and nginx are up but the requested build is not found (e.g. because that build number was skipped, as is the case here, or perhaps because that build has not yet been completed) then you'll get a 404 error.

If buildmaster is down but nginx is up you'll get a 50x error like 502 Bad Gateway or 504 Gateway Timeout.

If nginx is down you'll get no response.

**Comment by ryandesign** [comment]
Looks like all the builds have been imported now. Thanks!
