### ISSUE TITLE
Remove legacy 10.6-10.8 builders

### ISSUE THREAD

**Issue by ryandesign** [macports/macports-webapp#275]
From the web server logs on build.macports.org I saw attempts to retrieve build information for the 10.6-10.8 legacy builders:

```
136.243.18.213 - - [19/Apr/2021:20:50:17 +0000] "GET /json/builders/ports-10.8_x86_64_legacy-builder/builds/-1 HTTP/1.1" 404 153 "-" "Python-urllib/3.8" "-"
136.243.18.213 - - [19/Apr/2021:20:50:18 +0000] "GET /json/builders/ports-10.7_x86_64_legacy-builder/builds/-1 HTTP/1.1" 404 153 "-" "Python-urllib/3.8" "-"
136.243.18.213 - - [19/Apr/2021:20:50:21 +0000] "GET /json/builders/ports-10.6_x86_64_legacy-builder/builds/-1 HTTP/1.1" 404 153 "-" "Python-urllib/3.8" "-"
136.243.18.213 - - [19/Apr/2021:20:50:22 +0000] "GET /json/builders/ports-10.6_i386_legacy-builder/builds/-1 HTTP/1.1" 404 153 "-" "Python-urllib/3.8" "-"
```

These four builders no longer exist so you should remove everything about them from the web app.

**Comment by mojca** [comment]
I definitely agree that we should remove fetching the data from the legacy builders, but I don't think we need to remove the history of the builds.

**Comment by mojca** [comment]
@ryandesign: can you please just confirm whether these queries are still running from the new site? (The old site is still active.)

**Comment by arjunsalyan** [comment]
We no longer fetch data for these builders.
