### ISSUE TITLE
Tests (or refactor) parsing_scripts/git_update

### ISSUE THREAD

**Issue by umeshksingla** [macports/macports-webapp#28]
I am worried about `OSError` thrown in cases other than the two you mentioned above.

_Originally posted by @umeshksingla in https://github.com/_render_node/MDExOlB1bGxSZXF1ZXN0Mjg2NDkwNzY3/timeline/more_items_

**Comment by arjunsalyan** [comment]
The script was rewritten and the primary concern of this ticket was addressed.
