### ISSUE TITLE
Is django needed both outside and inside the requirements file to Travis?

### ISSUE THREAD

**Issue by umeshksingla** [macports/macports-webapp#29]
Thread: https://github.com/macports/macports-webapp/pull/13#discussion_r294192381

There's `Django==2.1.7` in requirements.txt which probably needs to be removed.

_Originally posted by @umeshksingla in https://github.com/macports/macports-webapp/pull/13_

**Comment by arjunsalyan** [comment]
@mojca previously suggested that we might want to test only for the latest versions.

Removing `Django` from `requirements.txt` would make us to install `django` separately (separately from `pip install -r requirements.txt`), and this is the only reason I am not sure about this. We may either remove the version and just let Travis test for the latest version, or may ourselves add some latest version. I have no clue about how to best deal with this?

**Comment by mojca** [comment]
No, I didn't want to suggest that we need to test **exclusively** the latest version. It doesn't hurt to have multiple tests setup, even if there's probably not much of a difference (I don't care that much if we have just one version tested). I would not remove django from that list, I would just probably remove the old hardcoded version.

It's two-fold problem. Either we put all the versions there and ensure that it will run forever, but we would eventually forget to update them (I noticed that @rajdeepbharati set up some bot to update dependencies versions in some of his repositories), or we risk that a newer version of one dependency will break the app, at which point we'll need to restrict it further later.

**Comment by arjunsalyan** [comment]
We are no longer testing with multiple Django versions, but just with the fixed version from requirements.txt. So I guess this issue is not relevant now.
