### ISSUE TITLE
Portindex json to use dictionary like structure

### ISSUE THREAD

**Issue by umeshksingla** [macports/macports-webapp#30]
In continuation of the conversation here: https://github.com/macports/macports-webapp/pull/13/files#r298847004

The format of portindex.json output doesn't directly allow us to access a port by its name and one has to loop over the entire list to find a port's details.

From Zulip:
> Mojca Miklavec: I forgot where this was mentioned. I've read somewhere that json isn't that useful as one cannot easily retrieve information about one particular port. Since we are messing up the format anyway, we can just as well change the existing array to a dictionary. It will consume some extra "bytes", but the file is already long anyway. I don't know if it actually affects processing efficiency, but it might effect readability of the update code.

**Comment by arjunsalyan** [comment]
Instead of changing the format of `PortIndex.json`, we are now using dictionaries internally in the app to speed up the lookup process.

**Comment by umeshksingla** [comment]
Since there are a lot of changes in other PRs open at the moment, I'd request you to add a link to the changes you mentioned here.

**Comment by arjunsalyan** [comment]
655922c36b97f3a0c743c53f8abc10b98042cf47

If this looks fine, I can reword this commit, to refer and close this issue.

Relevant conversation from zulip: https://macports-gsoc.zulipchat.com/#narrow/stream/201680-gsoc19-webapp/topic/General/near/170870778

**Comment by mojca** [comment]
I would say that since we decided not to implement this, we should simply close the ticket.
