### ISSUE TITLE
Clicking on the API link on the bottom is broken

### ISSUE THREAD

**Issue by rdbisme** [macports/macports-webapp#302]
The API link on the bottom of the page (from mobile, in the list of urls) is broken ☺ 
![Screenshot_20210720_192610](https://user-images.githubusercontent.com/8077364/126368657-a6590d9f-fa5f-4379-b8b1-d5da8396f277.jpg)

Is it normal?

**Comment by arjunsalyan** [comment]
No, it is not normal, it is broken. The documentation and the footer is pending an update.
