### ISSUE TITLE
Access to MacPorts trac

### ISSUE THREAD

**Issue by bestlem** [macports/macports-webapp#310]
I think there should be a link to the MacPorts trac from the main page.

The issues link surprised be to going to issue on the web site, Looking more carefully I can see that makes sense but with no link to Trac then it seems odd.

Currently how do you get to Trac via links, even Documentation does not have a link.

**Comment by mojca** [comment]
I'm not sure what exactly your proposal is.

**Comment by bestlem** [comment]
Minimum is at the bottom of https://ports.macports.org/ add a link to Trac under the macports heading ie a direct link.

My main point was more reporting the issue rather than a solution as I am not a good GUI designer, I can spot issues but not suggest solutions

**Comment by arjunsalyan** [comment]
If I am getting it right, the proposal is to provide a convenient way to report more issues with ports (on Trac). And also a link to 
trac in the footer.

For example we can have a button on every port page saying `Report an issue` which would take to the [new ticket page](https://trac.macports.org/newticket).

**Comment by mojca** [comment]
> For example we can have a button on every port page saying `Report an issue` which would take to the [new ticket page](https://trac.macports.org/newticket).

Well, in that case we could use directly something like

    https://trac.macports.org/newticket?port=gnuplot&cc=mojca

automatically filling in the port name and CC-ing maintainers. That sounds like a potentially cute idea.

**Comment by mojca** [comment]
@bestlem: just for clarification. My personal long term idea (not sure if it will ever get implemented) would be to somehow "merge" the main macports site with this one, so that both would have an uniform look and feel, probably a common header/footer, and ideally come from the same source code repository / the same server. There's more than just Trac missing among the links.

Note that each port has its own links to all the trac tickets that relate to that port already, but sure, there's no generic link, and I agree to a large extent that it would be useful to have one. Maybe just some rethinking whether we need to change anything else in the footer to make it clearer that one column contains links related to the web app, and the other one to the main MacPorts pages.

**Comment by bestlem** [comment]
Yes that makes sense - and I definitely agree with the last sentaece - the current setup confuses me

Actually I would go further. When using the site you do not care about the site you are interested in Macports. Looking at all the options under Quick Link I think none of them are needed as quick links. Put all the website things under one link.

**Comment by arjunsalyan** [comment]
Implemented in https://github.com/macports/macports-webapp/pull/331

**Comment by bestlem** [comment]
No it is not implemented.

The Quick links are still wrong - see most of tyhe issues reported are not for the site but are build issues

Secondly how do you access trac when there are no openm tickets.

**Comment by arjunsalyan** [comment]
I understand what you are trying to say here. Trac existed even when there was no Ports Website. You can always visit trac.macports.org which is a completely independent tool.

The website currently shows any open issues for the ports, and a direct link to create a new issue on Trac for that port.

Certainly there are improvements which can be done to this:

- it can be made more prominent that only open issues are being displayed.
- there can be a direct link to all the closed issues
- before someone is redirected to create a new issue, we could show the currently open issues.

But then we have to be careful that we do not end up doing too much. Trac is a mature independent tool, and we should not attempt to redo things which Trac is already very capable of doing.

And as the final remarks, we obviously lack contributors to implement all these on the ports website at this point of time.
