### ISSUE TITLE
Minor: Page title shows "Maintained by Me," when in the "Followed by Me" section

### ISSUE THREAD

**Issue by mascguy** [macports/macports-webapp#318]
A minor issue for sure, but would be nice to fix.

**Comment by mascguy** [comment]
Arjun, was this fixed? I'm not seeing any change in the page title...

**Comment by mascguy** [comment]
Never mind, it's fixed now. Thanks so much!

**Comment by arjunsalyan** [comment]
It takes 5-10 minutes for changes made here to get deployed.
