### ISSUE TITLE
Ordering messed up in `Port Health` list

### ISSUE THREAD

**Issue by jasonliu--** [macports/macports-webapp#320]
I just noticed that on the `Details` pages, the `Port Health` section appears to be displaying the various macOSes in the incorrect order. Specifically, `Snow Leopard (i386)` is currently listed between `Big Sur (x86_64)` and `Catalina`. I'm not 100% sure, but my sense is that the ordering used to be fine before, but might have gotten messed up starting when `Monterey` was added to the list. Seems like `Snow Leopard (i386)` should be listed after `Snow Leopard`, no?

And somewhat tangentially, shouldn't `Snow Leopard` be labelled as `Snow Leopard (x86_64)`? Or maybe `Snow Leopard (i386)` should be changed to be `Snow Leopard (32-bit)` and `Snow Leopard` labelled as `Snow Leopard (64-bit)`?

One final observation. Currently, the two `Monterey`s are listed with `x86_64` first and `arm64` second, while `Big Sur` has `arm64` listed first and `x86_64` second. Should probably keep the ordering consistent.

**Comment by arjunsalyan** [comment]
I think most of the concerns from this ticket are fixed, if you still feel something is off please reopen.

**Comment by arjunsalyan** [comment]
The suggestion to label `Snow Leopard (32-bit)` and `Snow Leopard (64-bit)` seems good to me, but then it would mean deviating from the buildbot convention.

**Comment by mascguy** [comment]
Looks great Arjun, thanks for the quick fix!

**Comment by jasonliu--** [comment]
Looks great to me. The suggestion for `Snow Leopard (32-bit)` and `(64-bit)` was only in the absence of something like `Snow Leopard (x86_64)`, which I see you have already added. Having `Snow Leopard (x86_64)` and `Snow Leopard (i386)` helps to keep things consistent, since we now also have `(arm64)` and `(x86_64)`. :smiley:
