### ISSUE TITLE
octave install fails under Monterey 

### ISSUE THREAD

**Issue by gjolleyrogers** [macports/macports-webapp#324]
As noted elsewhere, vecLibFort fails for Monterey. Attempted other variants. No joy. 
Please advise if there's a workaround.

Oh, and thanks for all the sterling work. 
G

--->  Fetching archive for vecLibFort
--->  Attempting to fetch vecLibFort-0.4.2_0.darwin_21.x86_64.tbz2 from https://packages.macports.org/vecLibFort
--->  Attempting to fetch vecLibFort-0.4.2_0.darwin_21.x86_64.tbz2 from https://pek.cn.packages.macports.org/macports/packages/vecLibFort
--->  Attempting to fetch vecLibFort-0.4.2_0.darwin_21.x86_64.tbz2 from http://jog.id.packages.macports.org/macports/packages/vecLibFort
--->  Building vecLibFort
Error: Failed to build vecLibFort: command execution failed
Error: See /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_devel_vecLibFort/vecLibFort/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets if you believe there
is a bug.
Error: Processing of port octave failed

**Comment by jmroot** [comment]
This issue tracker is only for issues with the ports.macports.org web app. The issue building vecLibFort on Monterey is being tracked here: https://trac.macports.org/ticket/63717

**Comment by bestlem** [comment]
Unfortunately there is no other place to report this from the main page - what links do you choose

**Comment by mojca** [comment]
The main website https://www.macports.org/ lists a link saying "Report a bug" leading to https://trac.macports.org/newticket.

**Comment by bestlem** [comment]
Yes but how do you get there from ports.macports.org when google has sent you here

**Comment by arjunsalyan** [comment]
That's a valid point @bestlem, we sometime planned to add a "Report an issue" button on the port page (displayed on ports.macports.org). That's on the to-do list.

**Comment by jmroot** [comment]
> That's on the to-do list.

As #310, specifically.
