### ISSUE TITLE
Maintainer facet lost when multiple facets enabled and going to the next page

### ISSUE THREAD

**Issue by herbygillot** [macports/macports-webapp#325]
In the ports search page, if you select both a `maintainer` and `category` facet, only the `category` facet remains selected when you go to the next page.

To reproduce:

1. Go to the port search page
2. Choose a `maintainer` in the maintainer panel at the top left
3. Choose a `category` in the category panel
4. Hit the blue search button to apply those facets
5. Click on Page 2
6. Observe the maintainer facet disappear, and results for Page 2 displaying for the `category` facet only

**Comment by arjunsalyan** [comment]
The fixes should take effect within next 15 minutes on the site.

UPDATE: Fixes deployed to ports.macports.org

**Comment by herbygillot** [comment]
Confirmed fixed, thank you very much @arjunsalyan
