### ISSUE TITLE
cscope not working after recent upgrade of mac ports using selupdate and upgrade of ports

### ISSUE THREAD

**Issue by sudheerhebbale** [macports/macports-webapp#330]
Installation and upgrade went through successfully

When I run cscope on commandline the following error gets thrown

$ cscope

dyld[39272]: symbol not found in flat namespace '_yylex'
Abort

Unable to figure out the issue

**Comment by jmroot** [comment]
This is not an issue with the MacPorts web app. Please report port bugs on Trac: https://guide.macports.org/chunked/project.html#project.tickets
