### ISSUE TITLE
sudo port install scrcpy ... Port scrcpy not found

### ISSUE THREAD

**Issue by itoldusoandso** [macports/macports-webapp#333]
I have installed MacPorts.
bash-3.2$ sudo port install scrcpy
Error: Port scrcpy not found

I don't know if this is question here or in scrcpy? 
https://github.com/Genymobile/scrcpy/issues/2256

Thank you for help.

**Comment by jmroot** [comment]
This tracker is for issues with the MacPorts web app only, so I am closing this. It looks like you might just need to sync your ports tree. If you need further assistance, please see: https://www.macports.org/contact.php

**Comment by Coool** [comment]
[scrcpy](https://github.com/Coool/scrcpy-macOS-Binaries) for macOS
