### ISSUE TITLE
Update to Solr 8.x

### ISSUE THREAD

**Issue by mascguy** [macports/macports-webapp#335]
It might be worthwhile to update to Solr 8, assuming there aren't any major breaking changes (and/or other issues). An added bonus is that MacPorts provides a port for the latest Solr 8 release, simplifying local development setup.

I'm also willing to help with this migration, if it's not straightforward.

**Comment by arjunsalyan** [comment]
We had to go with Solr 6.X because we use `django-haystack` for search and it only supports Solr 6.X . I am very doubtful if this upgrade would be possible as long as we use django-haystack. 
https://django-haystack.readthedocs.io/en/master/installing_search_engines.html

**Comment by mascguy** [comment]
> We had to go with Solr 6.X because we use `django-haystack` for search and it only supports Solr 6.X . I am very doubtful if this upgrade would be possible as long as we use django-haystack. 
> https://django-haystack.readthedocs.io/en/master/installing_search_engines.html

Makes sense, thanks for the info Arjun!
