### ISSUE TITLE
ports.macports.org missed at least one port: gcc10-bootstrap

### ISSUE THREAD

**Issue by catap** [macports/macports-webapp#336]
The url: https://ports.macports.org/port/gcc10-bootstrap/details/ says that port has been deleted.

But it quite alive: https://github.com/macports/macports-ports/blob/master/lang/gcc10-bootstrap/Portfile

**Comment by arjunsalyan** [comment]
The PortIndex is generated using the command `portindex -p macosx_19_i386` in a linux environment.

For a few ports, parsing errors are encountered, here is from the recent logs

```
Failed to parse file devel/icu58/Portfile: sysctl not available
Failed to parse file graphics/povray/Portfile: sysctl not available
Failed to parse file lang/gcc10-bootstrap/Portfile: sysctl not available
Failed to parse file math/pari/Portfile: sysctl not available
Failed to parse file security/cyrus-sasl2/Portfile: sysctl not available
```

`gcc10-bootstrap` falls in this list and hence it is not available in the PortIndex used by the website, that is why it is marked as deleted. There is an open Trac Ticket for the same https://trac.macports.org/ticket/62753

**Comment by catap** [comment]
@arjunsalyan can you try `portindex -p macosx_21_arm`? I guess that should help.

**Comment by jmroot** [comment]
As per the trac ticket, it's the ports, or more often the portgroups they include, that need to be fixed.
