### ISSUE TITLE
rubygems failure

### ISSUE THREAD

**Issue by russhousley** [macports/macports-webapp#341]
Rubygems depends on broken files.

~~~
$sudo port install rb-rubygems
--->  Computing dependencies for rb-rubygems
--->  Cleaning rb-rubygems
--->  Scanning binaries for linking errors
--->  Found 2 broken files, matching files to ports
Warning: No port p5.26-net-ssleay found in the index; can't rebuild
--->  Broken files found, but all associated ports are not in the index and so cannot be rebuilt.
$
~~~

**Comment by jmroot** [comment]
1. This is the issue tracker for the MacPorts web app only. Issues with ports should be reported at https://trac.macports.org/
2. `rb-rubygems` does not depend on `p5.26-net-ssleay`, rev-upgrade just runs after every installation and finds all broken files. `p5.26-net-ssleay` no longer exists in the ports tree, as the message says, so most likely you just want to uninstall it. You can find other such ports with `port echo obsolete`.
