### ISSUE TITLE
rust is listed as deleted

### ISSUE THREAD

**Issue by jmroot** [macports/macports-webapp#342]
https://ports.macports.org/port/rust/details/

My guess would be this is another parse failure like [#65183](https://trac.macports.org/ticket/65183), but I can't see the problem this time. @arjunsalyan, would you be able to check what the failure looks like?

Displaying the output of the most recent portindex run on the web app somewhere would be a useful feature, come to think of it.

**Comment by arjunsalyan** [comment]
Yes, this is a parse-failure

```
Failed to parse file lang/rust/Portfile: can't read "muniversal.architectures": can't read "universal_possible": can't read 
"configure.universal_archs": can't read "muniversal.can_run.x86_64": can't read "os.cpu64bit_capable": sysctl not available
```

This is the only failure.

We can display the output, yes. I will try to add raw outputs of this and some other background jobs somewhere to increase visibility.

**Comment by jmroot** [comment]
Thanks. Would you like me to open a separate issue for the feature request?

**Comment by arjunsalyan** [comment]
For some reason the parsing error with rust is still there

```
Failed to parse file lang/rust/Portfile: can't read "muniversal.architectures": can't read "universal_possible": can't read "configure.universal_archs": can't read "muniversal.can_run.x86_64": can't read "os.cpu64bit_capable": sysctl not available
```

**Comment by jmroot** [comment]
Oh yeah, portindex is run with -p, isn't it.

**Comment by arjunsalyan** [comment]
Yes, it is

```
portindex -p macosx_19_i386 -x
```
