### ISSUE TITLE
What happens when a port fails to compile (+universal) and there is no maintainer?

### ISSUE THREAD

**Issue by potterpg** [macports/macports-webapp#346]
What happens when a port fails to compile (+universal) and there is no maintainer?

ie [jemalloc?](https://ports.macports.org/port/jemalloc/details/)

The auto build build either an arm64 or an x86_64, so seems like no one would ever know if a +universal build fails.

How or who resolves this kind of issue?

**Comment by mascguy** [comment]
> What happens when a port fails to compile (+universal) and there is no maintainer?
> 
> ie [jemalloc?](https://ports.macports.org/port/jemalloc/details/)
> 
> The auto build build either an arm64 or an x86_64, so seems like no one would ever know if a +universal build fails.
> 
> How or who resolves this kind of issue?

Great question!

First search for existing open tickets for the port(s) in question, via Trac:
* https://trac.macports.org/wiki/Tickets

Alternatively, you're always welcome to ask such questions via our Users mailing list:
* https://lists.macports.org/mailman/listinfo/macports-users
