### ISSUE TITLE
@rpath problems of the gcc/gfortran libraries

### ISSUE THREAD

**Issue by xuhengdada** [macports/macports-webapp#349]
Can we choose to use absolute path rather than use @rpath for these libraries when we install the gcc with MacPorts?

It looks strange for me that the libraries of gcc/gfortran use "@rpath" while many other packages use the absolute PATH.

Actually the "@rpath" sometimes causes problems that other libraries cannot find these libraries who use "@rpath".

**Comment by jmroot** [comment]
This is the issue tracker for the MacPorts web app only. Issues with ports should be reported at https://trac.macports.org/

**Comment by xuhengdada** [comment]
Thank you @jmroot.
I also found the solvent at https://trac.macports.org/ticket/65510
