### ISSUE TITLE
Support sending stdlib information and displaying that statistics as well

### ISSUE THREAD

**Issue by mojca** [macports/macports-webapp#35]
I'm looking at [vtk stats](http://ec2-52-34-234-111.us-west-2.compute.amazonaws.com/port/vtk/?tab=stats).

![image](https://user-images.githubusercontent.com/15606/61158031-17398100-a4f8-11e9-9eac-5fb7049afdd7.png)

Curious enough our buildbot builds are failing, yet we have a user who has it installed on 10.5.

I miss two pieces of information here:
* One should be readily available: current platform (`build_arch`)
* The other one is missing and requires a fix of mpstats first: default `stdlib` setting, which can be either `libc++` or `stdlibc++`.

Displaying both pieces of information is only relevant on 10.6 and lower (`build_arch`) or 10.8 and lower (`stdlib`).

What I would be interested to know for macOS < 10.9 users of my own ports is what platform combination they are using. Maybe the following could be shown in the same bar, but with a different color, as in a [stacked bar chart](https://developers.google.com/chart/interactive/docs/gallery/columnchart#stacked-column-charts) for the y axis:
* x86_64/libc++ (default)
* x86_64/stdlibc++
* i386/libc++
* i386/stdlibc++
* ppc/<probably stdlibc++>

Displaying the graphs is not a super high priority, but we should try to get the missing stdlib information submitted.

Maybe we could also submit the default compiler setting.

**Comment by arjunsalyan** [comment]
I have enabled charts for `os_arch`.

For the other fix, I will start looking into how mpstats finds the required info.

**Comment by mojca** [comment]
Since the change was so trivial, I submitted a PR, so that you can implement the change in the graph faster :)

A less trivial (but also not that difficult, and much lower priority anyway) piece of information to extract would be:
* the default compiler on OS and the default compiler used for MacPorts
* a boolean values telling you whether default prefix is being used (I believe that one is stored in `macports::prefix`, but I don't want to leak personal info; we don't care where it is stored, only if it is default or not)
* default variants (`/opt/local/etc/macports/variants.conf`)
* maybe version of command-line tools when xcode is missing

**Comment by mojca** [comment]
Somewhat related to this, so I'm temporarily misusing the same ticket.

@satraul: After your project is finished & we start promoting that it might be ok not to install Xcode, I expect more users to install just command-line tools. In those cases `xcode_version` will likely return `none`, yet we could still submit the version of command-line tools. Would you be willing to look into ways to report CLT version when submitting statistics? Thanks.

**Comment by arjunsalyan** [comment]
> Since the change was so trivial, I submitted a PR, so that you can implement the change in the graph faster :)

Thank you very much.

> A less trivial (but also not that difficult, and much lower priority anyway) piece of information to extract would be:
> 
> * the default compiler on OS and the default compiler used for MacPorts

I will have to read more about it.

> * a boolean values telling you whether default prefix is being used (I believe that one is stored in `macports::prefix`, but I don't want to leak personal info; we don't care where it is stored, only if it is default or not)

We can simply check if it is "/opt/local/", right?

> * default variants (`/opt/local/etc/macports/variants.conf`)

I remember that we wanted to check if the default variant of the port was installed. Does this help in that by some sort of matching? I am sorry, I don't have much idea about how variants work.

**Comment by mojca** [comment]
To clarify as we discussed in the morning, here's how I would suggest to change the existing table:

![image](https://user-images.githubusercontent.com/15606/61999960-c071a100-b0cc-11e9-95f5-78742c303971.png)

```html
<script type="text/javascript">
    google.charts.load('current', {'packages':['corechart']});
    google.charts.setOnLoadCallback(drawChart);
    function drawChart() {
        var data = google.visualization.arrayToDataTable([
            ['OS Version', 'x86_64', 'x86_64/libstdc++', 'i386/libstdc++', 'powerpc/libstdc++',  {role: 'annotation'}],
                ['OS: 10.14', 17, , , ,  ''],
                ['OS: 10.13', 8, , , ,  ''],
                ['OS: 10.12', 2, , , ,  ''],
                ['OS: 10.9', 1, , , ,  ''],
                ['OS: 10.6', 1, 1, 2, ,  ''],
                ['OS: 10.5', , , , 1,  ''],
        ]);

    var options = {
        'title': 'OS Version and Architectures',
        isStacked: true,
        'chartArea': {left: 0, top: 10, width: "80%"}
    };

    var chart = new google.visualization.ColumnChart(document.getElementById('os-chart'));
    chart.draw(data, options);
  }
</script>
```

**Comment by jmroot** [comment]
Is there a bug somewhere or does some user really have their cxx_stdlib set to `libc`? Seen on e.g. http://ec2-52-34-234-111.us-west-2.compute.amazonaws.com/port/bzip2/?tab=stats&days=30&days_ago=0

**Comment by arjunsalyan** [comment]
> Is there a bug somewhere or does some user really have their cxx_stdlib set to `libc`? Seen on e.g. http://ec2-52-34-234-111.us-west-2.compute.amazonaws.com/port/bzip2/?tab=stats&days=30&days_ago=0

Thank you. This is a known bug. The `+` character is getting stripped in submissions.

**Comment by satraul** [comment]
> Somewhat related to this, so I'm temporarily misusing the same ticket.
> 
> @satraul: After your project is finished & we start promoting that it might be ok not to install Xcode, I expect more users to install just command-line tools. In those cases `xcode_version` will likely return `none`, yet we could still submit the version of command-line tools. Would you be willing to look into ways to report CLT version when submitting statistics? Thanks.

Hi, I've opened a pull request here report CLT version: https://github.com/macports/macports-ports/pull/4907

Note that it supports all CLT versions, including macOS <= 10.8 where we actually prefer Xcode's over CLT

**Comment by mojca** [comment]
> > Is there a bug somewhere or does some user really have their cxx_stdlib set to `libc`? Seen on e.g. http://ec2-52-34-234-111.us-west-2.compute.amazonaws.com/port/bzip2/?tab=stats&days=30&days_ago=0
> 
> Thank you. This is a known bug. The `+` character is getting stripped in submissions.

And it has already been fixed. Thanks a lot.
