### ISSUE TITLE
unable to build Scotch via macports

### ISSUE THREAD

**Issue by Yashwanth131091** [macports/macports-webapp#350]
**Please make sure the Issue you are creating is related to macports-webapp (the website running at ports.macports.org) only.**

For issues related to ports and MacPorts software, please use Trac:
- Trac: https://trac.macports.org
- Existing Tickets: https://trac.macports.org/wiki/Tickets

#### Explain the bug/suggestion/feature-request related to the website https://ports.macports.org below

I am trying to build scotch as mumps dependencies and turning up with this following error:

The following portion of lines are taken from the main.log file in the scotch directory after an unsuccessful run.

":info:build make[2]: Entering directory `/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_science_scotch/scotch/work/scotch_6.0.9/src/scotch'
:info:build /opt/local/bin/mpicc-mpich-mp -O3 -fPIC -Drestrict=__restrict -DCOMMON_FILE_COMPRESS_GZ -DCOMMON_PTHREAD -DCOMMON_PTHREAD_BARRIER -DCOMMON_RANDOM_FIXED_SEED -DCOMMON_TIMING_OLD -DSCOTCH_RENAME -DCOMMON_FILE_COMPRESS_BZ2 -DCOMMON_FILE_COMPRESS_LZMA -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -arch arm64 -I../../include -I../libscotch dggath.c -o dggath -L../../lib -lptscotch -lscotch -lptscotcherrexit -L/opt/local/lib -Wl,-headerpad_max_install_names -lz -lm -lpthread -lbz2 -llzma -Wl,-rpath,/opt/local/lib/libgcc -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -arch arm64
:info:build ld: in ../../lib/libptscotch.a(libscotch.a), archive member 'libscotch.a' with length 846440 is not mach-o or llvm bitcode file '../../lib/libptscotch.a' for architecture arm64
:info:build clang: error: linker command failed with exit code 1 (use -v to see invocation)
:info:build make[2]: *** [dggath] Error 1"

Please guide me on how to resolve this issue. I am currently using a M1 Pro chip built in 2021.

**Comment by jmroot** [comment]
Open a ticket on Trac and attach the log there.
