### ISSUE TITLE
Fetching archive failed: - sudo port install py38-scipy 

### ISSUE THREAD

**Issue by SkyForceCoder** [macports/macports-webapp#352]
Hi there,

I was installing  py38-scipy  using command -"sudo port install py38-scipy " 
I see below files were requested but did not exist in the given locations. 

Error: 

Attempting to fetch py38-scipy-1.9.3_0+gfortran+openblas.darwin_22.x86_64.tbz2 from https://packages.macports.org/py38-scipy
:debug:archivefetch Fetching archive failed: The requested URL returned error: 404

:msg:archivefetch --->  Attempting to fetch py38-scipy-1.9.3_0+gfortran+openblas.darwin_22.x86_64.tbz2 from https://kmq.jp.packages.macports.org/py38-scipy
:debug:archivefetch Fetching archive failed: The requested URL returned error: 404

:msg:archivefetch --->  Attempting to fetch py38-scipy-1.9.3_0+gfortran+openblas.darwin_22.x86_64.tbz2 from https://pek.cn.packages.macports.org/macports/packages/py38-scipy
:debug:archivefetch Fetching archive failed: The requested URL returned error: 404

Thanks!

**Comment by jmroot** [comment]
1. This is the issue tracker for the MacPorts web app running at ports.macports.org only. Issues installing ports should be reported at trac.macports.org.
2. There are no binaries for macOS 13 yet, so MacPorts will build from source after attempting to fetch the binary archive fails.

**Comment by SkyForceCoder** [comment]
Thanks! I reported this issue to  trac.macports.org -> https://trac.macports.org/ticket/66345#ticket
