### ISSUE TITLE
Poor site performance

### ISSUE THREAD

**Issue by jmroot** [macports/macports-webapp#353]
The site seems to be really slow at the moment. Pages are often taking 10+ seconds to load and are occasionally timing out completely.

**Comment by arjunsalyan** [comment]
CPU usage for the database has spiked up. I got some time to quickly run a quick cleanup of the database but that is not helping. I will also try to contact the hosting company if this is some underlying degradation on their end.

**Comment by arjunsalyan** [comment]
The performance seems to have returned to normal. This required both - some work with the database and a bit of tweaking from the hosting company.

**Comment by jmroot** [comment]
Great, I can confirm it seems OK again for me too. Thanks for working on it.
