### ISSUE TITLE
i install hexchat using macports, but don't know how can i start the apps to use it

### ISSUE THREAD

**Issue by fhazal** [macports/macports-webapp#359]
hye im new with macos, i already the application hexchat using sudo port install hexchat after it's finish install, i don't know how to start the apps,because there is no instruction how to start the app, can anybody help me

**Comment by ryandesign** [comment]
This GitHub repository is about the MacPorts web app. For questions about how to use MacPorts, you can ask on the [macports-users mailing list](https://lists.macports.org/mailman/listinfo/macports-users).
