### ISSUE TITLE
Add macOS Sonoma build information

### ISSUE THREAD

**Issue by ryandesign** [macports/macports-webapp#364]
Builds for macOS Sonoma x86_64 have begun; please begin importing this build information and add it to the port health.

Builds for macOS Sonoma arm64 have not yet begun but you can already begin polling buildbot for its status information.

**Comment by cjones051073** [comment]
It would be nice if this could be made automatic in someway, so it does not require someone to update something each year when a new OS comes along...

**Comment by arjunsalyan** [comment]
Thanks

There was some discussion about the automation here https://github.com/macports/macports-webapp/issues/117 .

Closing this as the Sonoma builders have been added.

**Comment by cjones051073** [comment]
https://ports.macports.org/port/gcc13/details/

Any reason you have not included `(x86_64)` in the Intel Sonoma name, to match what you do for all the other OSes that have both arm64 and x86_64 builds ?

**Comment by arjunsalyan** [comment]
Oh, my bad. Corrected it, thanks.

**Comment by cjones051073** [comment]
thanks!
