### ISSUE TITLE
Failed to install smokeping on macos

### ISSUE THREAD

**Issue by moshere-cirm** [macports/macports-webapp#366]
After running this command 
`sudo port install smokeping`
Successfully.
Failed to run `smokeping` with the following error
`ERROR: loading smokeping configuration file /opt/local/etc/smokeping/config: No such file or directory`

Running with Sonoma 14.0 on M1 Max

Thank you

**Comment by jmroot** [comment]
This issue tracker is for issues related to macports-webapp (the website running at ports.macports.org) only.

For issues related to ports and MacPorts software, please use Trac:
- Trac: https://trac.macports.org
- Existing Tickets: https://trac.macports.org/wiki/Tickets
