### ISSUE TITLE
Don't cache 5xx errors

### ISSUE THREAD

**Issue by jmroot** [macports/macports-webapp#378]
It appears that if a request results in a 504 error, Varnish will cache it for several minutes. It also appears that whatever is causing these occasional errors usually gets better in a much shorter time (since other pages of the same type are working). So perhaps it would be better not to cache 5xx responses at all, or only for a very short time.

**Comment by arjunsalyan** [comment]
Yes, this was happening. I have updated the config to not cache any 4XX or 5XX response, please reopen the ticket if you observe this again.

**Comment by jmroot** [comment]
Thanks. 4XX might be OK to cache, but I guess it's fine not to as long as there aren't too many requests for nonexistent pages.
