### ISSUE TITLE
Add anchors to all tables

### ISSUE THREAD

**Issue by mojca** [macports/macports-webapp#38]
Provide a way to link to all titles of tables, so that one can link to one individual table

**Comment by arjunsalyan** [comment]
I have added copyable links to all charts and tables for the stats pages (port stats and overall stats).

Or did you mean individual rows of the tables?

**Comment by mojca** [comment]
No, just a single link to one chart is fine.

**Comment by mojca** [comment]
The site is down, so I cannot test it, but let's close it as done.
