### ISSUE TITLE
Create a single paginated table with port installation statistics

### ISSUE THREAD

**Issue by mojca** [macports/macports-webapp#39]

**Comment by mojca** [comment]
Very cool!

What I miss most is some "accumulated sorting" (not sure how to call this). That is: when you first click that you want to sort by total number of installations, then you click requested number of installations, it could make sense to sort by requested number first. Then among the ports with the same number of requested installations, sort by the number of total installations. And finally by port name. In order to do this you might need to add some multi-indices to tables, and you would need to keep track of how sorting was requested. We only have three columns, so you would only need to remember the order of three values. Default sorting order could be (requested desc, total desc, name asc).

One personal request would be to add the display parameters to URL, so that clicking back in the browser would get you back to the previous view. Low priority. Something like `statistics/ports/?days=30,page=2,orderby=requested_desc-total_desc-name_asc`. The last one could be coded in a more compact way like `orderby=RTn` or anything else.

In the future it would be nice to see the following added to the table:
* a column indicating port health summary (it could be just a single symbol)
* a column indicating whether the port is outdated
* a separate filter, similar to "filter by port name" where one could filter by maintainer; then I could quickly check popularity, health status and outdatedness of all my ports

**Comment by arjunsalyan** [comment]
One problem I am facing with multi-field sorting is  priority- which fields to give priority while sorting. If I use the field selected first as the higher priority, then suppose the user wants to change the priority? What is the best way to allow this? A reset button?

**Comment by mojca** [comment]
I would start with default being
```
(requested DESC, total DESC, name ASC)
```
Now assume the user clicks on `requested ASC`. Then you change to
```
(requested ASC, total DESC, name ASC)
```
Now the user clicks on `total DESC`. You change the order into
```
(total DESC, requested ASC, name ASC)
```
Then the user clicks `name DESC`. So you change the order into
```
(name DESC, total DESC, requested ASC)
```
Basically you always keep the set of all three variables (and ideally also reflect those changes in page URL) and whenever the user clicks one of them, push that one to the front with the requested sorted direction. You don't really need to reset at any point (unless when loading a page again, in which case you would set the sorting order to default), you just keep repeating this cycle ad-infinity. There are only 6 permutations of the order (times 8 different sorting direction combinations).

I don't know whether you can create indices for these kind of searches (probably not unless you use materialized views).

This is just a random thought, I'm not saying it's the ideal solution. Did you now approximately understand what I wanted to suggest? Do you have any better ideas?

Optionally you could reflect the sorting order by highlighting the second and third selection in brighter shades of the same colour that you use to highlight the main selection.

(I liked the older version with arrows being next to each other slightly more that being stacked on top of each other, but that's just a matter of personal taste, so I don't really care. if it stays as it is now.)

**Comment by arjunsalyan** [comment]
Thank you so much for the explanation.

But one use I see of a multi-field sort is: I first click on `total desc`, and now for those ports with same number of total installations I want to sort them by `requested desc`- so I click on it (the priority still being `total desc`). The cycle you suggested will make `requested desc` as the priority as soon as I click on it.

Or I am missing something?

**Comment by arjunsalyan** [comment]
Oh, but you can always click on it again. Thanks, it is clear now.

**Comment by arjunsalyan** [comment]
Please now see: [Port Installations](http://ec2-52-34-234-111.us-west-2.compute.amazonaws.com/statistics/ports/) . I have implemented the discussed sorting. Please net me know if I got your suggestion right.

Then I will move on to adding the page state to the url.

NOTE: Some browsers might not show colours immediately because of the cached files.

**Comment by mojca** [comment]
Yes, it's precisely what I had in mind. It might make sense to ask others whether the interface is intuitive enough to them to use, but it does offer precisely all sorting options to users.

@mf2k had some feedback about other pages, so maybe he has something to say about this one as well?

**Comment by mf2k** [comment]
> @mf2k had some feedback about other pages, so maybe he has something to say about this one as well?

I do! :^)

Any column of numbers should be decimal point justified to make reading and comparing the numbers easier. Since they are counts, and thus integers, the numbers should be right aligned.

**Comment by mf2k** [comment]
Also, in the [Ports tab](http://ec2-52-34-234-111.us-west-2.compute.amazonaws.com), since we have a very large number of ports, I think having selectors by first letter of port name can be useful. So add a row with the letters of the alphabet. The selected results are the ports that start with that letter.

```
Browse by letter

a b c d ...

```

**Comment by mf2k** [comment]
Some wording/capitalization consistency changes on the Ports tab page:

- Change `Search by Description` to `Search by description`

- Change `Browse By Categories` to `Browse by category`. It is singular because only one category can be clicked on.

**Comment by mf2k** [comment]
On the [Statistics -> Top Ports tab](http://ec2-52-34-234-111.us-west-2.compute.amazonaws.com/statistics/), the numbers columns should be right justified. 

I like the alternate row coloring for the `Total Installations` table, please add that to the `Requested Installations` table.

**Comment by arjunsalyan** [comment]
> > @mf2k had some feedback about other pages, so maybe he has something to say about this one as well?
> 
> I do! :^)
> 
> Any column of numbers should be decimal point justified to make reading and comparing the numbers easier. Since they are counts, and thus integers, the numbers should be right aligned.

Thank you. We have numbers at many places. I will be doing this for all.

**Comment by arjunsalyan** [comment]
> Also, in the [Ports tab](http://ec2-52-34-234-111.us-west-2.compute.amazonaws.com), since we have a very large number of ports, I think having selectors by first letter of port name can be useful. So add a row with the letters of the alphabet. The selected results are the ports that start with that letter.
> 
> ```
> Browse by letter
> 
> a b c d ...
> ```

We actually had this before. But we decided to drop it some time ago. I could easily bring it back.

**Comment by mf2k** [comment]
> > Also, in the [Ports tab](http://ec2-52-34-234-111.us-west-2.compute.amazonaws.com), since we have a very large number of ports, I think having selectors by first letter of port name can be useful. So add a row with the letters of the alphabet. The selected results are the ports that start with that letter.
> > ```
> > Browse by letter
> > 
> > a b c d ...
> > ```
> 
> We actually had this before. But we decided to drop it some time ago. I could easily bring it back.

OK. Sorry I missed that conversation. If there was justification for leaving that out, then that is OK with me. Personally, I find such a selection method useful.

**Comment by mojca** [comment]
This can of course be an endless discussion, but I find both browse-by-category as well as browse-by-first-letter of very limited usability.

My favourite way would be to have a very decent search / filter functionality. Browsing all ports starting by letter P is pretty useless on its own. We are already able to search by port description or part of port name. We could probably support entering `^p` as port name filter to get all ports whose names start with letter `P`. And then you could use `^p5` to get some perl subports. But then we could add more filters:
* filter by description (show only ports which contain that string in short or long description)
* filter by maintainer (show only ports with no maintainer, only openmaintainer, only closedmaintainer, only those maintainer by the given github account or macports internal handle - where we could even have autocomplete functionality to enter maintainer)
* filter by category (where we could also offer autocomplete)
* only show outdated ports, only show ports with broken livecheck, only show ports which are up to date
* only show ports within a selected range of requested or total installations
* only show ports which were broken / fully functional / partially broken on the buildbot
* ...
