### ISSUE TITLE
Improve listings of port dependencies

### ISSUE THREAD

**Issue by mojca** [macports/macports-webapp#40]
When listing port dependencies, separately list different types of dependencies.

We would also like to see the reverse list: which ports depend on the port in question. (Could go to a separate ticket.)

**Comment by arjunsalyan** [comment]
> When listing port dependencies, separately list different types of dependencies.

Please check [this](http://ec2-52-34-234-111.us-west-2.compute.amazonaws.com/port/wget/?tab=summary) if it looks fine.

**Comment by mf2k** [comment]
Sorry for doing a drive by review. First of all, it looks great! The trailing commas in the Summary tab really bug me though - for dependencies, maintainers, categories and variants. How about getting rid of them entirely and just use a space as a separator (rather than comma and space now)?

**Comment by arjunsalyan** [comment]
> Sorry for doing a drive by review. First of all, it looks great! The trailing commas in the Summary tab really bug me though - for dependencies, maintainers, categories and variants. How about getting rid of them entirely and just use a space as a separator (rather than comma and space now)?

Thank you. I have removed the trailing comma. Do we still want to use just space as a separator?

**Comment by mojca** [comment]
I don't really care if it's space or comma, both work just fine.

As for the change: how difficult would it be to put the labels (test, build, extract, ...) below Dependencies and remove bold styling? Then the actual dependencies would be left-justified just below everything else.

Also, I would probably replace "Dependencies" with "Depends on". And then add "Dependency of" below to list which ports depend on that port.

**Comment by mf2k** [comment]
I prefer space only as a separator. It's easier to copy and paste into a command line statement that way.

**Comment by mojca** [comment]
Thank you very much for adding dependent ports. But you probably want to put those on the bottom, as is evident in [this example](http://ec2-52-34-234-111.us-west-2.compute.amazonaws.com/port/gettext/?tab=summary). And we may want to sort them.

**Comment by mf2k** [comment]
I agree that the dependencies should be sorted by name. Also please right justify the dependency types `test:`, `build:`, `extract:`, `lib:`, etc.

**Comment by arjunsalyan** [comment]
Thanks.

I have:
1. sorted the dependencies and dependents by port names
2. right aligned the dependency types.
3. moved `Dependency Of` below `Depends On`.

**Comment by mojca** [comment]
Awesome, thank you very much.

Now, looking at [python27](http://ec2-52-34-234-111.us-west-2.compute.amazonaws.com/port/python27/?tab=summary) for example it probably makes sense to do the splitting by dependency type of "Dependency of" as well, to help maintainer decide which ports might need a revbump or testing after updating that particular port.

And if there are no dependencies maybe print something like the `/` or `-` character, or `(none)`.

**Comment by mf2k** [comment]
Looking good! I think it makes sense to also sort the variants by name.

**Comment by arjunsalyan** [comment]
> Awesome, thank you very much.
> 
> Now, looking at [python27](http://ec2-52-34-234-111.us-west-2.compute.amazonaws.com/port/python27/?tab=summary) for example it probably makes sense to do the splitting by dependency type of "Dependency of" as well, to help maintainer decide which ports might need a revbump or testing after updating that particular port.
> 
> And if there are no dependencies maybe print something like the `/` or `-` character, or `(none)`.

Thank you, I have addressed both.

**Comment by arjunsalyan** [comment]
> Looking good! I think it makes sense to also sort the variants by name.

Thanks, sorted the variants.

**Comment by mf2k** [comment]
I was playing with shrinking and enlarging the window size to see how dynamically the pages cope with that. It shrinks pretty well, but it does not expand to fill, for example, a full screen window on my 24 inch monitor. Can you allow the column sizes to expand more?

In particular, with python27 as an example, there are *lots* of ports (like py27-*) that depend on it that are listed. Yet even with a wide window, the column doesn't get that wide and so it scrolls down a lot. Instead a bunch of white space appears on the sides. Also, maybe moving the small tables on the right to the top of the page makes sense so that they don't take up so much column space. This will allow the main summary table to take up the full window width.

**Comment by arjunsalyan** [comment]
> I was playing with shrinking and enlarging the window size to see how dynamically the pages cope with that. It shrinks pretty well, but it does not expand to fill, for example, a full screen window on my 24 inch monitor. Can you allow the column sizes to expand more?

The header of the website expands to the entire width of the viewport, rest of the site (contents) are wrapped inside bootstrap's `container` class which has a max-width of 1200px. I feel, this is a standard size for websites that do not expand to the entire width, for example the contents of GitHub itself.

However, we may decide if we want to go for a full-width design.
