### ISSUE TITLE
Format of the License field

### ISSUE THREAD

**Issue by umeshksingla** [macports/macports-webapp#44]
Not a super important issue but the license field can be improved sometime in the future to have a consistent format and without braces on the ends.
1. https://ports.macports.org/port/automake
2. https://ports.macports.org/port/aqbanking5

**Comment by mojca** [comment]
However I would like to ask the experts for some hints first. I believe there is an actual difference when braces are used. In some cases it may mean "either one licence or the other", in others it may mean "both licences apply".

**Comment by jmroot** [comment]
https://github.com/macports/macports-base/blob/master/src/port/port.tcl#L2186

So `MIT {PSF ZPL} {Apache-2 BSD}` is displayed in more human-readable form as `MIT and (PSF or ZPL) and (Apache-2 or BSD)`.

**Comment by mojca** [comment]
@jmroot: thank you. I never noticed that it's formatted in this way when you use `port info`.

I have two questions though:
* How could we use this function directly to change what gets written to `portindex.tcl`? (I assume we can copy-paste the code, but it would be nicer to have just one reusable function called multiple times.)
* Why the following discrepancy?
```
> port info automake
automake @1.16.1_1 (devel)

Description:          Automake is a tool for automatically generating Makefile.in files from files called Makefile.am. Each Makefile.am is basically a series of
                      make variable definitions, with rules being thrown in occasionally. The generated Makefile.in files are compliant with the GNU Makefile
                      standards.
Homepage:             https://www.gnu.org/software/automake

Build Dependencies:   autoconf
Platforms:            darwin, freebsd
License:              (GPL-2+ or Permissive)
Maintainers:          none
```

```
> port info --license automake
license: {GPL-2+ Permissive}
```

My suggestion would be to change this in `portindex.tcl` and don't do anything in the app.

**Comment by jmroot** [comment]
We need it to be machine-readable in the PortIndex.

**Comment by mojca** [comment]
Sorry, I meant `PortIndex.json`, rather than `PortIndex` itself. (I made a typo in the file extension.)
Proper machine-readability in the scope of `json` would likely mean encoding that information in `json` constructs, but that would likely be an overkill. In itself (when forgetting `tcl`) the format with parenthesis and using `and`/`or` is probably equally machine-readable if one would want to do something further with "`MIT and (PSF or ZPL) and (Apache-2 or BSD)`" than when using curly braces?
