### ISSUE TITLE
Used stacked charts for port version vs. time

### ISSUE THREAD

**Issue by mojca** [macports/macports-webapp#48]
Here are my screenshots with an example of how we could present the versions of various ports through time:
![image](https://user-images.githubusercontent.com/15606/62000267-ed28b700-b0d2-11e9-9c85-5308011599e2.png)

Source:
```html
<script type="text/javascript">
  google.charts.load('current', {'packages':['corechart']});
  google.charts.setOnLoadCallback(drawChart);

  function drawChart() {
    var data = google.visualization.arrayToDataTable([
      ['Month', '6.9.9-40_6', '6.9.9-40_5', '6.9.9-26_0'],
      ['Jun 2019', 12, 19, 1],
      ['Jul 2019', 14,  5, 0],
    ]);

    var options = {
      title: 'Version',
      hAxis: {title: 'Month (ImageMagick; oldest on top)',  titleTextStyle: {color: '#333'}},
      vAxis: {minValue: 0},
      isStacked: true,
      height: 250,
      'chartArea': {left: 0, top: 0, width: "80%"}
    };

    var chart = new google.visualization.AreaChart(document.getElementById('chart_div3'));
    chart.draw(data, options);
  }
</script>
```

For reference, here's how a similar graph for gettext looks on the old page:
![image](https://user-images.githubusercontent.com/15606/62000372-a5eff580-b0d5-11e9-94da-c94ba48d1e67.png)

To some extent I believe that we might want to remove revisions when plotting this graph. Not 100% sure though, and it's not a high priority, so we can leave it as it is for now.

**Comment by arjunsalyan** [comment]
![Screenshot 2019-08-02 at 6 50 00 PM](https://user-images.githubusercontent.com/40331563/62372944-5a669d00-b556-11e9-9f35-1bcf8ee8133c.png)

Here is how the charts looks for ImageMagick. I have even deployed the changes, so it can be seen running here: http://ec2-52-34-234-111.us-west-2.compute.amazonaws.com/port/ImageMagick/?tab=stats&days=30&days_ago=0

I have mixed feelings about this chart, so I can't really decide.

**Comment by mojca** [comment]
When you add zeros it looks better
![image](https://user-images.githubusercontent.com/15606/62378814-ee7c3880-b545-11e9-844d-eb8e8083081d.png)
