### ISSUE TITLE
"Trac Tickets" view lists unrelated ports

### ISSUE THREAD

**Issue by neverpanic** [macports/macports-webapp#50]
The list of trac tickets for a port uses substring matching, not word matching to find ports. This leads an incorrect list of tickets for ports whose name is a substring of a different port.

This does happen, for example, for the `tig` port, because `tig` is a substring of `tigervnc` and `antigen`: http://ec2-52-34-234-111.us-west-2.compute.amazonaws.com/port/tig/?tab=tickets.

**Comment by arjunsalyan** [comment]
Thank you very much. I just noticed that we are using the following URL to fetch:
```
https://trac.macports.org/query?status=!closed&port=~tig
```
This probably needs to be changed to:
```
https://trac.macports.org/query?status=!closed&port=tig
```

**Comment by raimue** [comment]
[TracQuery](https://trac.macports.org/wiki/TracQuery) is simply not able to express such a specific match. It only has the "contains" operator, which is a substring match. Your proposal would be an exact match only and miss tickets that list more than one port.

You could use this report which uses the Postgres `~*` operator directly against the database with [this SQL query](https://trac.macports.org/report?id=16&format=sql). We could create additional reports or modify this one as needed. With this we can match beginning and end of word like in this regular expression:

https://trac.macports.org/report/16?PORT=\mvim\M

**Comment by arjunsalyan** [comment]
Thank you very much. I tried the following regex:

https://trac.macports.org/report/16?max=100&PORT=(^|\s)vim($|\s)

It mostly seems to match words. Could you please share your views on the use of this one?

**Comment by mojca** [comment]
> We could create additional reports or modify this one as needed.

This would definitely be extremely helpful.

For example, I would love it if entering port name into https://trac.macports.org/wiki/Tickets would result in correct results.

Both queries (exact match and partial match) do have their value. I sometimes search for "perl5" for example, and it's useful to see results for all perl versions. But most of the time I really want just exact matches.

> https://trac.macports.org/report/16?max=100&PORT=(^|\s)vim($|\s)

Cool. This seems to work correctly.
* It doesn't have false positives in the sense of returning, say, `erlang` tickets when you ask for `lang`.
* It seems to return all tickets when the port field contains multiple ports, at least for the few cases I tested.

I guess this solves the problem as far as app is concerned. But I don't know if it can be applied to cases like this one on a wiki page or a ticket:
```
[[TicketQuery(status=assigned|new|reopened&port~=perl5)]]
```
Would a custom query also solve such cases?

**Comment by raimue** [comment]
Is there any problem with `\m` or why did you use `(^|\s)` instead?

No, unfortunately this report won't help with a TicketQuery and there is no solution to that. It is a [long-standing limitation](https://trac.edgewall.org/ticket/7558) in the Trac query language.

**Comment by arjunsalyan** [comment]
> Is there any problem with `\m` or why did you use `(^|\s)` instead?

`(^|\s)` worked for matching a complete word.

I thought we could solve the problem if we match complete word (port-name)

**Comment by raimue** [comment]
It would help if you could give examples to show where the proposed regex did not work as expected...

However, I figured it out now that `\m` will also match `.` or `_` as word boundaries and that is not what we want, as these are allowed characters in a port name. Therefore the regex you proposed works better.
