### ISSUE TITLE
Searching within a maintainer's ports doesn't work

### ISSUE THREAD

**Issue by jmroot** [macports/macports-webapp#52]
For example, typing `py-` in the search box on http://ec2-52-34-234-111.us-west-2.compute.amazonaws.com/maintainer/github/jmroot/ gives an error.

**Comment by arjunsalyan** [comment]
Thank you very much. It should work now. In safari you might need to clear website data to quickly view the changes.

**Comment by jmroot** [comment]
Thanks, confirming that it works now.
