### ISSUE TITLE
Broken maintainer's page when invalid maintainer handle

### ISSUE THREAD

**Issue by umeshksingla** [macports/macports-webapp#63]
We need to rethink a little around the maintainer's page. I was of the opinion that when clicked on a maintainer's name in the port-summary page, it'll simply go to another page but instead, it tries to load the content over it. (Browser's backward and forward buttons don't work with the maintainer's page, to verify). We really don't need any in-place modification of content like this.

Also, passing a wrong maintainer's handle breaks the app on accessing `all_ports` variable, e.g. http://\<ec2\>/maintainer/github/`umesh`.  The correct URL was http://\<ec2\>/maintainer/github/`umeshksingla`. I don't think the query gets fired.

**Comment by umeshksingla** [comment]
Another issue which could be related to above is that the maintainer name is not available when you search by a string:

<img width="1205" alt="Screen Shot 2019-08-03 at 1 17 08 PM" src="https://user-images.githubusercontent.com/9131544/62409169-1379b580-b5f1-11e9-8d4e-18f5dc2e27e9.png">

With random search string:

<img width="1159" alt="Screen Shot 2019-08-03 at 1 17 20 PM" src="https://user-images.githubusercontent.com/9131544/62409172-15437900-b5f1-11e9-9fb1-64ddccd276bb.png">

It works fine when you search for ports for a variant or a category. I think we should just keep it similar to them unless there were issues I am not aware of.

**Comment by umeshksingla** [comment]
Sorry, I forgot to press the send button in the morning.

The problem is probably with this part in `views.py`:
```py
def search_ports_in_maintainer(request):
    query = request.GET.get('name', '')
    name = request.GET.get('maintainers__name')
    github = request.GET.get('maintainers__github')
    if name is None:
        search_in = github
    else:
        search_in = name
    ...
```
From ajax-maintainers.js:
```js
'maintainers__name': $('#maintainers__name').text(),
'maintainers__github': $('#maintainers__github').text()
```
where `$().text()` submits empty string (`""`), so it's never `None`. But please check if it is indeed the case.

**Comment by arjunsalyan** [comment]
I have tried to address some issues.

http://ec2-52-34-234-111.us-west-2.compute.amazonaws.com/maintainer/github/ryandesign/
