### ISSUE TITLE
Small UX inconsistency for the radio buttons

### ISSUE THREAD

**Issue by rdbisme** [macports/macports-webapp#65]
![Screenshot 2019-08-03 at 11 16 58](https://user-images.githubusercontent.com/8077364/62410020-41a2c980-b5e0-11e9-90f2-bca7b5009b65.png)
Maybe add a bit of padding between the radio button and the text `Search by port-name` and `Search by description`?

**Comment by arjunsalyan** [comment]
Thank you.
