### ISSUE TITLE
UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead.

### ISSUE THREAD

**Issue by neverpanic** [macports/macports-webapp#75]
I currently get an email for every cronjob run because the cronjobs generate output on stderr. The output is:

```
/usr/local/lib/python3.6/dist-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
```

From the linked documentation, it seems we should change the entry for `psycopg2` entry in requirements.txt to `psycopg2>=2.7,<2.8 --no-binary psycopg2`.

**Comment by arjunsalyan** [comment]
> From the linked documentation, it seems we should change the entry for `psycopg2` entry in requirements.txt to `psycopg2>=2.7,<2.8 --no-binary psycopg2`.

Doing this change does hide the warning.
