### ISSUE TITLE
Please display Categories in column-major order

### ISSUE THREAD

**Issue by jdberry** [macports/macports-webapp#85]
The web app is looking good!

One suggestion: It would be helpful if you displayed the Category list in column-major order: it's difficult to scan it as it is in row-major order.

Thx!

**Comment by mojca** [comment]
I agree with this sentiment, and it should be straightforward to fix.

(That said, I'm not sure if browsing by category is really that useful.)

What I would like to see on the site if it remains is the count of (active?) ports belonging to that category. A single sql query should be sufficient to get the full table `(category_name, port_count)`.

The list could look like this:
```
amusements (7)    fonts (19)        math (738)
aqua (739)        frameworks (4)    matlab (1)
archivers (121)   fuse (23)         ml (13)
...
```

**Comment by mojca** [comment]
And `Installations this month = NA` on the link that follows is also strange.

**Comment by arjunsalyan** [comment]
Thank you, these changes are now live at: http://ec2-52-34-234-111.us-west-2.compute.amazonaws.com

You may need to clear website data or do hard refresh, as it involves changes to CSS. Please let me know any other improvements.

These will soon get deployed to ports.macports.org (the update cycle is 5 hours I guess).

**Comment by mojca** [comment]
Thank you.

**Comment by jdberry** [comment]
Thx, @arjunsalyan. That looks a lot better!
